using SIE.Services.Info.Atributos;
using SIE.Services.Info.Enums;

namespace SIE.Services.Polizas.Modelos
{
    internal class PolizaDetalleModel
    {
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaGanado, Orden = 3, Desplazamiento = 2, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaGanadoDurango, Orden = 3, Desplazamiento = 2, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaVenta, Orden = 1, Desplazamiento = 2, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaMuerte, Orden = 1, Desplazamiento = 2, Alineacion = "center")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaCompra, Orden = 1, Alineacion = "center")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaAjuste, Orden = 1, Desplazamiento = 2, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaAjuste, Orden = 1, Desplazamiento = 2, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.PaseProceso, Orden = 1, Desplazamiento = 2, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.ProduccionAlimento, Orden = 1, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaCompraMateriaPrima, Orden = 1, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaTraspaso, Orden = 1, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaConsumo, Orden = 1, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaVentaProducto, Orden = 1, Alineacion = "center")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaTraspaso, Orden = 1, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaTraspasoSAP, Orden = 1, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.PolizaMuerteTransito, Orden = 1, Desplazamiento = 2, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaMuerteIntensiva, Orden = 1, Desplazamiento = 2, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaVentaIntensiva, Orden = 1, Desplazamiento = 2, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaMuerteEnTransito, Orden = 1, Desplazamiento = 2, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaVentaEnTransito, Orden = 1, Desplazamiento = 2, Alineacion = "right")]
        public string CantidadCabezas { get; set; }

        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaGanado, Orden = 4, Alineacion = "left")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaGanadoDurango, Orden = 4, Alineacion = "left")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaVenta, Orden = 2, Alineacion = "left")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaMuerte, Orden = 2, Alineacion = "left")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaCompra, Orden = 2, Alineacion = "left")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaAjuste, Orden = 2, Desplazamiento = 2, Alineacion = "left")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaAjuste, Orden = 2, Alineacion = "left")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.PaseProceso, Orden = 2, Alineacion = "left")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.ProduccionAlimento, Orden = 3, Alineacion = "left")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaCompraMateriaPrima, Orden = 2, Alineacion = "left")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaTraspaso, Orden = 3, Alineacion = "left")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaConsumo, Orden = 3, Alineacion = "left")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaVentaProducto, Orden = 2, Alineacion = "left")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaTraspaso, Orden = 3, Alineacion = "left")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaTraspasoSAP, Orden = 3, Alineacion = "left")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.PolizaMuerteTransito, Orden = 2, Alineacion = "left")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaMuerteIntensiva, Orden = 2, Alineacion = "left")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaVentaIntensiva, Orden = 2, Alineacion = "left")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaMuerteEnTransito, Orden = 2,  Alineacion = "left")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaVentaEnTransito, Orden = 2, Alineacion = "left")]
        public string TipoGanado { get; set; }

        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaVenta, Orden = 3, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaMuerte, Orden = 3, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.ProduccionAlimento, Orden = 5, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaTraspaso, Orden = 5, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaConsumo, Orden = 5, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaCompra, Orden = 6, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaTraspaso, Orden = 5, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaTraspasoSAP, Orden = 5, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.PolizaMuerteTransito, Orden = 3, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaMuerteIntensiva, Orden = 3, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaVentaIntensiva, Orden = 3, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaMuerteEnTransito, Orden = 3, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaVentaEnTransito, Orden = 3, Alineacion = "right")]
        public string PesoTotal { get; set; }

        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaGanado, Orden = 8, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaGanadoDurango, Orden = 8, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaVenta, Orden = 4, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaMuerte, Orden = 4, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.ProduccionAlimento, Orden = 2, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaTraspaso, Orden = 2, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaConsumo, Orden = 2, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaTraspaso, Orden = 2, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaTraspasoSAP, Orden = 2, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.PolizaMuerteTransito, Orden = 4, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaMuerteIntensiva, Orden = 4, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaVentaIntensiva, Orden = 4, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaMuerteEnTransito, Orden = 4, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaVentaEnTransito, Orden = 4, Alineacion = "right")]
        public string PesoPromedio { get; set; }

        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaVenta, Orden = 5, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaMuerte, Orden = 5, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaCompra, Orden = 8, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaAjuste, Orden = 6, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaAjuste, Orden = 7, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.PaseProceso, Orden = 7, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaCompraMateriaPrima, Orden = 7, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.PolizaMuerteTransito, Orden = 5, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaMuerteIntensiva, Orden = 5, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaVentaIntensiva, Orden = 5, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaMuerteEnTransito, Orden = 5, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaVentaEnTransito, Orden = 5, Alineacion = "right")]
        public string PrecioPromedio { get; set; }

        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaGanado, Orden = 9, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaGanadoDurango, Orden = 9, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaVenta, Orden = 6, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaMuerte, Orden = 6, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaCompra, Orden = 9, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaAjuste, Orden = 7, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaAjuste, Orden = 8, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.PaseProceso, Orden = 8, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.ProduccionAlimento, Orden = 7, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaCompraMateriaPrima, Orden = 8, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaTraspaso, Orden = 7, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaConsumo, Orden = 7, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaTraspaso, Orden = 7, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaTraspasoSAP, Orden = 7, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.PolizaMuerteTransito, Orden = 6, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaMuerteIntensiva, Orden = 6, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaVentaIntensiva, Orden = 6, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaMuerteEnTransito, Orden = 6, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaVentaEnTransito, Orden = 6, Alineacion = "right")]
        public string ImportePromedio { get; set; }

        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaGanado, Orden = 5, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaGanadoDurango, Orden = 5, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaVenta, Orden = 7, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaMuerte, Orden = 7, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaCompra, Orden = 10, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.PaseProceso, Orden = 9, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.ProduccionAlimento, Orden = 8, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaCompraMateriaPrima, Orden = 9, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaTraspaso, Orden = 8, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaConsumo, Orden = 8, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaVentaProducto, Orden = 7, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaTraspaso, Orden = 8, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaTraspasoSAP, Orden = 8, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.PolizaMuerteTransito, Orden = 7, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaMuerteIntensiva, Orden = 7, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaVentaIntensiva, Orden = 7, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaMuerteEnTransito, Orden = 7, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaVentaEnTransito, Orden = 7, Alineacion = "right")]
        public string PrecioVenta { get; set; }

        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaGanado, Orden = 6, Desplazamiento = 2, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaGanadoDurango, Orden = 6, Desplazamiento = 2, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaVenta, Orden = 8, Desplazamiento = 2, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaMuerte, Orden = 8, Desplazamiento = 2, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaCompra, Orden = 11, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.PaseProceso, Orden = 10, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaCompraMateriaPrima, Orden = 10, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaVentaProducto, Orden = 8, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.PolizaMuerteTransito, Orden = 8, Desplazamiento = 2, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaMuerteIntensiva, Orden = 8, Desplazamiento = 2, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaVentaIntensiva, Orden = 8, Desplazamiento = 2, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaMuerteEnTransito, Orden = 8, Desplazamiento = 2, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaVentaEnTransito, Orden = 8, Desplazamiento = 2, Alineacion = "right")]
        public string ImporteVenta { get; set; }

        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaVenta, Orden = 9, Alineacion = "left")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaMuerte, Orden = 9, Alineacion = "left")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaCompra, Orden = 7, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaAjuste, Orden = 6, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.PaseProceso, Orden = 6, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaCompraMateriaPrima, Orden = 6, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaVentaProducto, Orden = 6, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.PolizaMuerteTransito, Orden = 9, Alineacion = "left")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaMuerteIntensiva, Orden = 9, Alineacion = "left")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaVentaIntensiva, Orden = 9, Alineacion = "left")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaMuerteEnTransito, Orden = 9, Alineacion = "left")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaVentaEnTransito, Orden = 9, Alineacion = "left")]
        public string Corral { get; set; }

        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaGanado, Orden = 7, Alineacion = "left")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaGanadoDurango, Orden = 7, Alineacion = "left")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaVenta, Orden = 10, Alineacion = "left")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaMuerte, Orden = 10, Alineacion = "left")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaCompra, Orden = 3, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaAjuste, Orden = 3, Alineacion = "left")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaAjuste, Orden = 3, Alineacion = "left")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.PaseProceso, Orden = 3, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaCompraMateriaPrima, Orden = 3, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaVentaProducto, Orden = 3, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.PolizaMuerteTransito, Orden = 10, Alineacion = "left")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaMuerteIntensiva, Orden = 10, Alineacion = "left")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaVentaIntensiva, Orden = 10, Alineacion = "left")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaMuerteEnTransito, Orden = 10,  Alineacion = "left")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaVentaEnTransito, Orden = 10, Alineacion = "left")]
        public string Lote { get; set; }

        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaGanado, Orden = 1, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaGanadoDurango, Orden = 1, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaCompra, Orden = 4, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaAjuste, Orden = 4, Desplazamiento = 2, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaAjuste, Orden = 4, Desplazamiento = 2, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.PaseProceso, Orden = 4, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaCompraMateriaPrima, Orden = 4, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaVentaProducto, Orden = 4, Alineacion = "right")]
        public string PesoOrigen { get; set; }

        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaGanado, Orden = 2, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaGanadoDurango, Orden = 2, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaCompra, Orden = 5, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaAjuste, Orden = 5, Alineacion = "left")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaAjuste, Orden = 5, Desplazamiento = 2, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.PaseProceso, Orden = 5, Desplazamiento = 2, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.EntradaCompraMateriaPrima, Orden = 5, Desplazamiento = 2, Alineacion = "right")]
        [AtributoDetallePoliza(TipoPoliza = TipoPoliza.SalidaVentaProducto, Orden = 5, Desplazamiento = 2, Alineacion = "right")]
        public string PesoLlegada { get; set; }
    }
}
