//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIE.Services.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceServices {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceServices() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIE.Services.Properties.ResourceServices", typeof(ResourceServices).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un problema al buscar los modulos..
        /// </summary>
        internal static string AlertaModulo_ErrorBusqueda {
            get {
                return ResourceManager.GetString("AlertaModulo_ErrorBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Folio no permitido, el destino del producto es una bodega externa..
        /// </summary>
        internal static string BasculaMateriaPrima_MsgFolioEsDeBodegaExterna {
            get {
                return ResourceManager.GetString("BasculaMateriaPrima_MsgFolioEsDeBodegaExterna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El folio de la boleta no está activo. Favor de validar..
        /// </summary>
        internal static string BasculaMateriaPrima_MsgFolioInactivo {
            get {
                return ResourceManager.GetString("BasculaMateriaPrima_MsgFolioInactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe configuracion de rango para el producto:.
        /// </summary>
        internal static string BoletaRecepcion_ErrorRangos {
            get {
                return ResourceManager.GetString("BoletaRecepcion_ErrorRangos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El archivo esta en uso. Favor de validar..
        /// </summary>
        internal static string ConfigurarFormula_ArchivoEnUso {
            get {
                return ResourceManager.GetString("ConfigurarFormula_ArchivoEnUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El archivo excel no contiene registros. Favor de validar..
        /// </summary>
        internal static string ConfigurarFormula_ArchivoNoContieneRegistros {
            get {
                return ResourceManager.GetString("ConfigurarFormula_ArchivoNoContieneRegistros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El archivo seleccionado no cuenta con la estructura definida. Favor de validar..
        /// </summary>
        internal static string ConfigurarFormula_ArchivoNoTieneLaEstructura {
            get {
                return ResourceManager.GetString("ConfigurarFormula_ArchivoNoTieneLaEstructura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver los identificadores de la pestaña adjunta &quot;Tipo de Ganado&quot;. Ej.: Fórmula para &quot;Becerro Liviano&quot; y &quot;Becerro&quot;. Escribimos lo siguiente: Tipo Ganado: &quot;1|2&quot;..
        /// </summary>
        internal static string ConfigurarFormula_ComentarioEjemploLlenarTipoGanado {
            get {
                return ResourceManager.GetString("ConfigurarFormula_ComentarioEjemploLlenarTipoGanado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En el archivo se encuentran datos en blanco. Favor de validar..
        /// </summary>
        internal static string ConfigurarFormula_DatosEnBlanco {
            get {
                return ResourceManager.GetString("ConfigurarFormula_DatosEnBlanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a , Los días de estancia máximo deben ser mayor o igual a los días de estancia mínimo. Favor de validar..
        /// </summary>
        internal static string ConfigurarFormula_DiasEstancia {
            get {
                return ResourceManager.GetString("ConfigurarFormula_DiasEstancia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Días Estancia Máximo.
        /// </summary>
        internal static string ConfigurarFormula_DiasEstanciaMaximo {
            get {
                return ResourceManager.GetString("ConfigurarFormula_DiasEstanciaMaximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Días Estancia Mínimo.
        /// </summary>
        internal static string ConfigurarFormula_DiasEstanciaMinimo {
            get {
                return ResourceManager.GetString("ConfigurarFormula_DiasEstanciaMinimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a , Los días de transición máximo deben ser mayor o igual a los días de transición mínimo. Favor de validar..
        /// </summary>
        internal static string ConfigurarFormula_DiasTransicion {
            get {
                return ResourceManager.GetString("ConfigurarFormula_DiasTransicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Días Transición Máximo.
        /// </summary>
        internal static string ConfigurarFormula_DiasTransicionMaximo {
            get {
                return ResourceManager.GetString("ConfigurarFormula_DiasTransicionMaximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Días Transición Mínimo.
        /// </summary>
        internal static string ConfigurarFormula_DiasTransicionMinimo {
            get {
                return ResourceManager.GetString("ConfigurarFormula_DiasTransicionMinimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disponibilidad.
        /// </summary>
        internal static string ConfigurarFormula_Disponibilidad {
            get {
                return ResourceManager.GetString("ConfigurarFormula_Disponibilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En la fórmula: .
        /// </summary>
        internal static string ConfigurarFormula_EnLaFormula {
            get {
                return ResourceManager.GetString("ConfigurarFormula_EnLaFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fórmula.
        /// </summary>
        internal static string ConfigurarFormula_Formula {
            get {
                return ResourceManager.GetString("ConfigurarFormula_Formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fórmula:.
        /// </summary>
        internal static string ConfigurarFormula_FormulaNoExiste {
            get {
                return ResourceManager.GetString("ConfigurarFormula_FormulaNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a , no existe en el catalogo de fórmulas. Favor de validar..
        /// </summary>
        internal static string ConfigurarFormula_FormulaNoExiste2 {
            get {
                return ResourceManager.GetString("ConfigurarFormula_FormulaNoExiste2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fórmula Siguiente.
        /// </summary>
        internal static string ConfigurarFormula_FormulaSiguiente {
            get {
                return ResourceManager.GetString("ConfigurarFormula_FormulaSiguiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a , El peso inicio máximo deben ser mayor o igual a el peso inicio mínimo. Favor de validar..
        /// </summary>
        internal static string ConfigurarFormula_PesoInicio {
            get {
                return ResourceManager.GetString("ConfigurarFormula_PesoInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Peso Inicio Máximo.
        /// </summary>
        internal static string ConfigurarFormula_PesoInicioMaximo {
            get {
                return ResourceManager.GetString("ConfigurarFormula_PesoInicioMaximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Peso Inicio Mínimo.
        /// </summary>
        internal static string ConfigurarFormula_PesoInicioMinimo {
            get {
                return ResourceManager.GetString("ConfigurarFormula_PesoInicioMinimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Peso Salida.
        /// </summary>
        internal static string ConfigurarFormula_PesoSalida {
            get {
                return ResourceManager.GetString("ConfigurarFormula_PesoSalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Ganado.
        /// </summary>
        internal static string ConfigurarFormula_PestañaTipoGanado {
            get {
                return ResourceManager.GetString("ConfigurarFormula_PestañaTipoGanado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione un valor de la lista..
        /// </summary>
        internal static string ConfigurarFormula_SeleccioneValorDeLista {
            get {
                return ResourceManager.GetString("ConfigurarFormula_SeleccioneValorDeLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Ganado.
        /// </summary>
        internal static string ConfigurarFormula_TipoGanado {
            get {
                return ResourceManager.GetString("ConfigurarFormula_TipoGanado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a , No tiene especificado los tipos de ganado. Favor de validar..
        /// </summary>
        internal static string ConfigurarFormula_TipoGanadoFaltante {
            get {
                return ResourceManager.GetString("ConfigurarFormula_TipoGanadoFaltante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a , Contiene tipos de ganado inválidos. Favor de validar..
        /// </summary>
        internal static string ConfigurarFormula_TipoGanadoInvalido {
            get {
                return ResourceManager.GetString("ConfigurarFormula_TipoGanadoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración de Fórmulas.
        /// </summary>
        internal static string ConfigurarFormula_TituloExcel {
            get {
                return ResourceManager.GetString("ConfigurarFormula_TituloExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los valores capturados en el archivo no cumplen con el formato correcto. Favor de validar..
        /// </summary>
        internal static string ConfigurarFormula_ValoresFormatoCorrecto {
            get {
                return ResourceManager.GetString("ConfigurarFormula_ValoresFormatoCorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor Introducido no es valido..
        /// </summary>
        internal static string ConfigurarFormula_ValorInvalido {
            get {
                return ResourceManager.GetString("ConfigurarFormula_ValorInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dólar.
        /// </summary>
        internal static string ContratoBL_DescripcionMonedaDolar {
            get {
                return ResourceManager.GetString("ContratoBL_DescripcionMonedaDolar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DOLAR.
        /// </summary>
        internal static string ContratoBL_DescripcionMonedaDolarMayuscula {
            get {
                return ResourceManager.GetString("ContratoBL_DescripcionMonedaDolarMayuscula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pesos.
        /// </summary>
        internal static string ContratoBL_DescripcionMonedaPesos {
            get {
                return ResourceManager.GetString("ContratoBL_DescripcionMonedaPesos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El proveedor seleccionado debe tener un almacen asignado..
        /// </summary>
        internal static string ContratoBL_MensajeProveedorAlmacen {
            get {
                return ResourceManager.GetString("ContratoBL_MensajeProveedorAlmacen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un problema al intentar envía el correo..
        /// </summary>
        internal static string Correo_ErrorInesperado {
            get {
                return ResourceManager.GetString("Correo_ErrorInesperado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron los parámetros del los destinatarios del correo..
        /// </summary>
        internal static string Correo_ErrorParametrosCorreoDestino {
            get {
                return ResourceManager.GetString("Correo_ErrorParametrosCorreoDestino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron los parámetros del servidor de correo..
        /// </summary>
        internal static string Correo_ErrorParametrosServidor {
            get {
                return ResourceManager.GetString("Correo_ErrorParametrosServidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existen destinatarios para enviar el correo..
        /// </summary>
        internal static string Correo_SinDestinatario {
            get {
                return ResourceManager.GetString("Correo_SinDestinatario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se tiene configurado un almacén general para esta organización. Favor de validar..
        /// </summary>
        internal static string CosteoConsumoForraje_AlmacenGeneral {
            get {
                return ResourceManager.GetString("CosteoConsumoForraje_AlmacenGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Existen camiones en el reparto,  que no están registrados en el catálogo de camiones. Favor de Verificar..
        /// </summary>
        internal static string DescargaDataLink_msgCamionNoAsignado {
            get {
                return ResourceManager.GetString("DescargaDataLink_msgCamionNoAsignado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró archivo en la ruta configurada..
        /// </summary>
        internal static string DescargarDataLink_ArchivoNoExiste {
            get {
                return ResourceManager.GetString("DescargarDataLink_ArchivoNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El archivo no cuenta con datos..
        /// </summary>
        internal static string DescargarDataLink_ArchivoSinDatos {
            get {
                return ResourceManager.GetString("DescargarDataLink_ArchivoSinDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un problema al buscar el archivo DataLink..
        /// </summary>
        internal static string DescargarDataLink_ErrorInesperado {
            get {
                return ResourceManager.GetString("DescargarDataLink_ErrorInesperado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .BK1.
        /// </summary>
        internal static string DescargarDataLink_ExtencionArchivoFinal {
            get {
                return ResourceManager.GetString("DescargarDataLink_ExtencionArchivoFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .BK9.
        /// </summary>
        internal static string DescargarDataLink_ExtencionArchivoInicial {
            get {
                return ResourceManager.GetString("DescargarDataLink_ExtencionArchivoInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .DAT.
        /// </summary>
        internal static string DescargarDataLink_ExtencionArchivoPrincipal {
            get {
                return ResourceManager.GetString("DescargarDataLink_ExtencionArchivoPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .BK.
        /// </summary>
        internal static string DescargarDataLink_ExtencionParcial {
            get {
                return ResourceManager.GetString("DescargarDataLink_ExtencionParcial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha ingresada no coincide con la fecha del archivo. Favor de verificar..
        /// </summary>
        internal static string DescargarDataLink_FechaNoValida {
            get {
                return ResourceManager.GetString("DescargarDataLink_FechaNoValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La carga se realizo correctamente..
        /// </summary>
        internal static string DescargarDataLink_GuradadoOk {
            get {
                return ResourceManager.GetString("DescargarDataLink_GuradadoOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se cargo ningún registro..
        /// </summary>
        internal static string DescargarDataLink_NoSecargo {
            get {
                return ResourceManager.GetString("DescargarDataLink_NoSecargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 20.
        /// </summary>
        internal static string DescargarDataLink_PorcionAno {
            get {
                return ResourceManager.GetString("DescargarDataLink_PorcionAno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La ruta configurada no existe o no se puede acceder..
        /// </summary>
        internal static string DescargarDataLink_RutaNoExiste {
            get {
                return ResourceManager.GetString("DescargarDataLink_RutaNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El corral ya no tiene la capacidad. Favor de Verificar..
        /// </summary>
        internal static string EntradaEnfermeria_msgLoteSinCapacidad {
            get {
                return ResourceManager.GetString("EntradaEnfermeria_msgLoteSinCapacidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acción a Seguir:       Metafilaxia ( X )       Normal (   ).
        /// </summary>
        internal static string EvaluacionPartida_AccionASeguirMetafilaxia {
            get {
                return ResourceManager.GetString("EvaluacionPartida_AccionASeguirMetafilaxia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Justificación:.
        /// </summary>
        internal static string EvaluacionPartida_AccionASeguirMetafilaxiaJustificacion {
            get {
                return ResourceManager.GetString("EvaluacionPartida_AccionASeguirMetafilaxiaJustificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acción a Seguir:       Metafilaxia (   )       Normal ( X ).
        /// </summary>
        internal static string EvaluacionPartida_AccionASeguirNormal {
            get {
                return ResourceManager.GetString("EvaluacionPartida_AccionASeguirNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cbz:.
        /// </summary>
        internal static string EvaluacionPartida_Cbz {
            get {
                return ResourceManager.GetString("EvaluacionPartida_Cbz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FENVIZ-07-122.
        /// </summary>
        internal static string EvaluacionPartida_CodigoISO {
            get {
                return ResourceManager.GetString("EvaluacionPartida_CodigoISO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Corral:.
        /// </summary>
        internal static string EvaluacionPartida_Corral {
            get {
                return ResourceManager.GetString("EvaluacionPartida_Corral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evaluador:.
        /// </summary>
        internal static string EvaluacionPartida_Evaluador {
            get {
                return ResourceManager.GetString("EvaluacionPartida_Evaluador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de evaluación:.
        /// </summary>
        internal static string EvaluacionPartida_FechaEvaluacion {
            get {
                return ResourceManager.GetString("EvaluacionPartida_FechaEvaluacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 02 DE ENERO DEL 2015.
        /// </summary>
        internal static string EvaluacionPartida_FechaISO {
            get {
                return ResourceManager.GetString("EvaluacionPartida_FechaISO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de llegada:.
        /// </summary>
        internal static string EvaluacionPartida_FechaLlegada {
            get {
                return ResourceManager.GetString("EvaluacionPartida_FechaLlegada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hora de Evaluación:.
        /// </summary>
        internal static string EvaluacionPartida_HoraEvaluacion {
            get {
                return ResourceManager.GetString("EvaluacionPartida_HoraEvaluacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inv final:.
        /// </summary>
        internal static string EvaluacionPartida_InventarioFinal {
            get {
                return ResourceManager.GetString("EvaluacionPartida_InventarioFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inv inicial:.
        /// </summary>
        internal static string EvaluacionPartida_InventarioInicial {
            get {
                return ResourceManager.GetString("EvaluacionPartida_InventarioInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nota: Para aplicar Metafilaxia debe cumplir con 4 puntos. El Jefe de Sanidad puede confirmar o rechazar la decisión de aplicar Metafilaxia, aplique o no los 4 puntos..
        /// </summary>
        internal static string EvaluacionPartida_Nota {
            get {
                return ResourceManager.GetString("EvaluacionPartida_Nota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de partida:.
        /// </summary>
        internal static string EvaluacionPartida_NumPartida {
            get {
                return ResourceManager.GetString("EvaluacionPartida_NumPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procedencia de Animales:.
        /// </summary>
        internal static string EvaluacionPartida_ProcedenciaAnimales {
            get {
                return ResourceManager.GetString("EvaluacionPartida_ProcedenciaAnimales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rev. 9.
        /// </summary>
        internal static string EvaluacionPartida_RevisionISO {
            get {
                return ResourceManager.GetString("EvaluacionPartida_RevisionISO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evaluación de Riesgo para Complejo Respiratorio Bovino.
        /// </summary>
        internal static string EvaluacionPartida_SubTituloImpresion {
            get {
                return ResourceManager.GetString("EvaluacionPartida_SubTituloImpresion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evaluación de riesgos en las partidas.
        /// </summary>
        internal static string EvaluacionPartida_TituloImpresion {
            get {
                return ResourceManager.GetString("EvaluacionPartida_TituloImpresion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total:.
        /// </summary>
        internal static string EvaluacionPartida_Total {
            get {
                return ResourceManager.GetString("EvaluacionPartida_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La factura no fue generada, no se encontraron los datos de la factura..
        /// </summary>
        internal static string FacturaElectronica_MensajeErrorAlConsultarDatos {
            get {
                return ResourceManager.GetString("FacturaElectronica_MensajeErrorAlConsultarDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al generar la factura..
        /// </summary>
        internal static string FacturaElectronica_MensajeErrorAlGenerarFactura {
            get {
                return ResourceManager.GetString("FacturaElectronica_MensajeErrorAlGenerarFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El directorio configurado para la factura no existe. Favor de verificar..
        /// </summary>
        internal static string FacturaElectronica_MensajeErrorDirectorioNoExiste {
            get {
                return ResourceManager.GetString("FacturaElectronica_MensajeErrorDirectorioNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La factura no fue generada, el folio de la factura no esta configurado..
        /// </summary>
        internal static string FacturaElectronica_MensajeErrorFolioFactura {
            get {
                return ResourceManager.GetString("FacturaElectronica_MensajeErrorFolioFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La factura no fue generada, faltan parametros de configuración. Favor de verificar..
        /// </summary>
        internal static string FacturaElectronica_MensajeErrorParametros {
            get {
                return ResourceManager.GetString("FacturaElectronica_MensajeErrorParametros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La factura no fue generada, la ruta del archivo no esta configurada..
        /// </summary>
        internal static string FacturaElectronica_MensajeErrorRutaXml {
            get {
                return ResourceManager.GetString("FacturaElectronica_MensajeErrorRutaXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La factura no fue generada, el número de serie de la factura no esta configurado..
        /// </summary>
        internal static string FacturaElectronica_MensajeErrorSerie {
            get {
                return ResourceManager.GetString("FacturaElectronica_MensajeErrorSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay animales pendientes por facturar..
        /// </summary>
        internal static string GanadoIntensivoBL_ErrorAnimalesFacturados {
            get {
                return ResourceManager.GetString("GanadoIntensivoBL_ErrorAnimalesFacturados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incidencia Cerrada.
        /// </summary>
        internal static string Incidencia_Cerrada {
            get {
                return ResourceManager.GetString("Incidencia_Cerrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incidencia Registrada.
        /// </summary>
        internal static string Incidencia_Registrada {
            get {
                return ResourceManager.GetString("Incidencia_Registrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incidencia Vencida.
        /// </summary>
        internal static string Incidencia_Vencida {
            get {
                return ResourceManager.GetString("Incidencia_Vencida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al generar los movimientos del inventario.
        /// </summary>
        internal static string InventarioNormal_ErrorMovimientos {
            get {
                return ResourceManager.GetString("InventarioNormal_ErrorMovimientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron corrales para la organizacion..
        /// </summary>
        internal static string PolizaSalidaMuerteGanadoTransito_CorralesNoEncontrados {
            get {
                return ResourceManager.GetString("PolizaSalidaMuerteGanadoTransito_CorralesNoEncontrados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontro el costo. CostoID = {0}..
        /// </summary>
        internal static string PolizaSalidaMuerteGanadoTransito_CostoIdNoEncontrado {
            get {
                return ResourceManager.GetString("PolizaSalidaMuerteGanadoTransito_CostoIdNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Costo de ganado no encontrado..
        /// </summary>
        internal static string PolizaSalidaMuerteGanadoTransito_CostosGanadoNoEncontrado {
            get {
                return ResourceManager.GetString("PolizaSalidaMuerteGanadoTransito_CostosGanadoNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron costos activos..
        /// </summary>
        internal static string PolizaSalidaMuerteGanadoTransito_CostosNoEncontrados {
            get {
                return ResourceManager.GetString("PolizaSalidaMuerteGanadoTransito_CostosNoEncontrados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se proporcionaron detalles de salida de ganado en tránsito..
        /// </summary>
        internal static string PolizaSalidaMuerteGanadoTransito_DetalleSalidaGanadoTransitoNoProporcionados {
            get {
                return ResourceManager.GetString("PolizaSalidaMuerteGanadoTransito_DetalleSalidaGanadoTransitoNoProporcionados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NO EXISTE CONFIGURACION PARA EL COSTO {0}..
        /// </summary>
        internal static string PolizaSalidaMuerteIntensiva_msgErrorClaveContableAbono {
            get {
                return ResourceManager.GetString("PolizaSalidaMuerteIntensiva_msgErrorClaveContableAbono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El archivo de programación de corte de ganado se encuentra en uso..
        /// </summary>
        internal static string ProgramacionCorteImpresion_ArchivoEnUso {
            get {
                return ResourceManager.GetString("ProgramacionCorteImpresion_ArchivoEnUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cabezas.
        /// </summary>
        internal static string ProgramacionCorteImpresion_EncCabezas {
            get {
                return ResourceManager.GetString("ProgramacionCorteImpresion_EncCabezas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Corral.
        /// </summary>
        internal static string ProgramacionCorteImpresion_EncCorral {
            get {
                return ResourceManager.GetString("ProgramacionCorteImpresion_EncCorral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Días.
        /// </summary>
        internal static string ProgramacionCorteImpresion_EncDias {
            get {
                return ResourceManager.GetString("ProgramacionCorteImpresion_EncDias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evaluación.
        /// </summary>
        internal static string ProgramacionCorteImpresion_EncEvaluacion {
            get {
                return ResourceManager.GetString("ProgramacionCorteImpresion_EncEvaluacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Entrada.
        /// </summary>
        internal static string ProgramacionCorteImpresion_EncFechaEntrada {
            get {
                return ResourceManager.GetString("ProgramacionCorteImpresion_EncFechaEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Garrapata.
        /// </summary>
        internal static string ProgramacionCorteImpresion_EncGarrapata {
            get {
                return ResourceManager.GetString("ProgramacionCorteImpresion_EncGarrapata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a H.
        /// </summary>
        internal static string ProgramacionCorteImpresion_EncHembras {
            get {
                return ResourceManager.GetString("ProgramacionCorteImpresion_EncHembras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M.
        /// </summary>
        internal static string ProgramacionCorteImpresion_EncMachos {
            get {
                return ResourceManager.GetString("ProgramacionCorteImpresion_EncMachos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Origen.
        /// </summary>
        internal static string ProgramacionCorteImpresion_EncOrigen {
            get {
                return ResourceManager.GetString("ProgramacionCorteImpresion_EncOrigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a # Partida.
        /// </summary>
        internal static string ProgramacionCorteImpresion_EncPartida {
            get {
                return ResourceManager.GetString("ProgramacionCorteImpresion_EncPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total de cabezas a trabajar:.
        /// </summary>
        internal static string ProgramacionCorteImpresion_EncTotalTitulo {
            get {
                return ResourceManager.GetString("ProgramacionCorteImpresion_EncTotalTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha:.
        /// </summary>
        internal static string ProgramacionCorteImpresion_Fecha {
            get {
                return ResourceManager.GetString("ProgramacionCorteImpresion_Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dddd dd \de MMMM yyyy.
        /// </summary>
        internal static string ProgramacionCorteImpresion_FechaFormato {
            get {
                return ResourceManager.GetString("ProgramacionCorteImpresion_FechaFormato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Folio: .
        /// </summary>
        internal static string ProgramacionCorteImpresion_Folio {
            get {
                return ResourceManager.GetString("ProgramacionCorteImpresion_Folio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EN-51/1.
        /// </summary>
        internal static string ProgramacionCorteImpresion_FormatoReporte {
            get {
                return ResourceManager.GetString("ProgramacionCorteImpresion_FormatoReporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagenes\\skLogo.png.
        /// </summary>
        internal static string ProgramacionCorteImpresion_Logo {
            get {
                return ResourceManager.GetString("ProgramacionCorteImpresion_Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrada a Inventario Recepción Materia Prima.
        /// </summary>
        internal static string RecepcionMateriaPrima_ObservacionMovimientos {
            get {
                return ResourceManager.GetString("RecepcionMateriaPrima_ObservacionMovimientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El arete ya fue revisado. Favor de verificar..
        /// </summary>
        internal static string RevisionImplante_msgAreteExiste {
            get {
                return ResourceManager.GetString("RevisionImplante_msgAreteExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El arete ingresado no existe. Favor de verificar..
        /// </summary>
        internal static string RevisionImplante_msgAreteInvalido {
            get {
                return ResourceManager.GetString("RevisionImplante_msgAreteInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El arete no corresponde al corral ingresado. Favor de verificar..
        /// </summary>
        internal static string RevisionImplante_msgCorralDiferente {
            get {
                return ResourceManager.GetString("RevisionImplante_msgCorralDiferente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El corral ingresado no existe. Favor de verificar..
        /// </summary>
        internal static string RevisionImplante_msgCorralNoExiste {
            get {
                return ResourceManager.GetString("RevisionImplante_msgCorralNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El corral ingresado no corresponde a producción. Favor de verificar..
        /// </summary>
        internal static string RevisionImplante_msgCorralNoProductivo {
            get {
                return ResourceManager.GetString("RevisionImplante_msgCorralNoProductivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El corral ingresado no tiene movimientos. Favor de verificar..
        /// </summary>
        internal static string RevisionImplante_msgCorralSinMovimientos {
            get {
                return ResourceManager.GetString("RevisionImplante_msgCorralSinMovimientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es necesario primero seleccionar un corral. Favor de verificar..
        /// </summary>
        internal static string RevisionImplante_msgFaltaCorral {
            get {
                return ResourceManager.GetString("RevisionImplante_msgFaltaCorral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe agregar por lo menos un arete para poder continuar..
        /// </summary>
        internal static string RevisionImplante_msgFaltanAretes {
            get {
                return ResourceManager.GetString("RevisionImplante_msgFaltanAretes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos guardados con éxito..
        /// </summary>
        internal static string RevisionImplante_msgGuardado {
            get {
                return ResourceManager.GetString("RevisionImplante_msgGuardado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El corral ingresado no tiene lote activo. Favor de verificar..
        /// </summary>
        internal static string RevisionImplante_msgLoteInactivo {
            get {
                return ResourceManager.GetString("RevisionImplante_msgLoteInactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El arete ingresado no tiene movimientos. Favor de verificar..
        /// </summary>
        internal static string RevisionImplante_msgSinMovimientos {
            get {
                return ResourceManager.GetString("RevisionImplante_msgSinMovimientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El arete (ARETE) ya fue revisado el día de hoy. Favor de verificar..
        /// </summary>
        internal static string RevisionImplante_msgYaRevisado {
            get {
                return ResourceManager.GetString("RevisionImplante_msgYaRevisado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione.
        /// </summary>
        internal static string RevisionImplante_Seleccione {
            get {
                return ResourceManager.GetString("RevisionImplante_Seleccione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los siguientes ajustes se rechazaron automaticamente al no contar con suficiente inventario {0}..
        /// </summary>
        internal static string SolicitudAutorizacionBL_AutorizacionRechazadas {
            get {
                return ResourceManager.GetString("SolicitudAutorizacionBL_AutorizacionRechazadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rechazo Automatico.
        /// </summary>
        internal static string SolicitudAutorizacionBL_RechazoAutomatico {
            get {
                return ResourceManager.GetString("SolicitudAutorizacionBL_RechazoAutomatico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al intentar validar el limite de credito del cliente, no se pudo tener conexion con el servicio web.
        /// </summary>
        internal static string validarLimiteCredito_ErrorConsumoServicio {
            get {
                return ResourceManager.GetString("validarLimiteCredito_ErrorConsumoServicio", resourceCulture);
            }
        }
		
        /// <summary>
        ///   Busca una cadena traducida similar a Respuesta del servicio de validacion de limite de credito no configurada.
        /// </summary>
        internal static string validarLimiteCredito_RespuestaServicioDesconocida {
            get {
                return ResourceManager.GetString("validarLimiteCredito_RespuestaServicioDesconocida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin respuesta del servicio de validacion de limite de credito.
        /// </summary>
        internal static string validarLimiteCredito_SinRespuestaServicio {
            get {
                return ResourceManager.GetString("validarLimiteCredito_SinRespuestaServicio", resourceCulture);
            }
        }
    }
}
