//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuKarne.Controls.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuKarne.Controls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar.
        /// </summary>
        public static string Ayuda_Agregar {
            get {
                return ResourceManager.GetString("Ayuda_Agregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        public static string Ayuda_Buscar {
            get {
                return ResourceManager.GetString("Ayuda_Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Ayuda_Cancelar {
            get {
                return ResourceManager.GetString("Ayuda_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtros.
        /// </summary>
        public static string Ayuda_GrupoHeader {
            get {
                return ResourceManager.GetString("Ayuda_GrupoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al consultar los valores de ayuda.
        /// </summary>
        public static string Ayuda_MensajeError {
            get {
                return ResourceManager.GetString("Ayuda_MensajeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de.
        /// </summary>
        public static string PaginacionControl_De {
            get {
                return ResourceManager.GetString("PaginacionControl_De", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página.
        /// </summary>
        public static string PaginacionControl_Pagina {
            get {
                return ResourceManager.GetString("PaginacionControl_Pagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultados por página.
        /// </summary>
        public static string PaginacionControl_Resultados_Pagina {
            get {
                return ResourceManager.GetString("PaginacionControl_Resultados_Pagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Registros.
        /// </summary>
        public static string PaginacionControl_TotalRegistros {
            get {
                return ResourceManager.GetString("PaginacionControl_TotalRegistros", resourceCulture);
            }
        }
    }
}
