//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18063
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIE.Services.ServicioPolizasCancelacion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://SuKarne.com/pi/LOGIN/Cancelar_DoctosContables", ConfigurationName="ServicioPolizasCancelacion.SI_LOGIN_CancelarDoctos")]
    public interface SI_LOGIN_CancelarDoctos {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación SI_LOGIN_CancelarDoctos no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SIE.Services.ServicioPolizasCancelacion.SI_LOGIN_CancelarDoctosResponse SI_LOGIN_CancelarDoctos(SIE.Services.ServicioPolizasCancelacion.SI_LOGIN_CancelarDoctosRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://SuKarne.com/pi/LOGIN/Cancelar_DoctosContables")]
    public partial class DT_LOGIN_CancelarDoctos_ItemItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sociedadField;
        
        private string norefField;
        
        private string periodoField;
        
        private string clase_docField;
        
        private string archivoField;
        
        private string divisionField;
        
        private string fecha_cancField;
        
        private string doc_sapField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string sociedad {
            get {
                return this.sociedadField;
            }
            set {
                this.sociedadField = value;
                this.RaisePropertyChanged("sociedad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string noref {
            get {
                return this.norefField;
            }
            set {
                this.norefField = value;
                this.RaisePropertyChanged("noref");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
                this.RaisePropertyChanged("periodo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string clase_doc {
            get {
                return this.clase_docField;
            }
            set {
                this.clase_docField = value;
                this.RaisePropertyChanged("clase_doc");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string archivo {
            get {
                return this.archivoField;
            }
            set {
                this.archivoField = value;
                this.RaisePropertyChanged("archivo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string division {
            get {
                return this.divisionField;
            }
            set {
                this.divisionField = value;
                this.RaisePropertyChanged("division");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string fecha_canc {
            get {
                return this.fecha_cancField;
            }
            set {
                this.fecha_cancField = value;
                this.RaisePropertyChanged("fecha_canc");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string doc_sap {
            get {
                return this.doc_sapField;
            }
            set {
                this.doc_sapField = value;
                this.RaisePropertyChanged("doc_sap");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://SuKarne.com/pi/LOGIN/Cancelar_DoctosContables")]
    public partial class DT_SAP_CancelarDoctos_ResItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string nUMBERField;
        
        private string tYPEField;
        
        private string mESSAGEField;
        
        private string mESSAGE_V1Field;
        
        private string mESSAGE_V2Field;
        
        private string mESSAGE_V3Field;
        
        private string mESSAGE_V4Field;
        
        private string sYSTEMField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string NUMBER {
            get {
                return this.nUMBERField;
            }
            set {
                this.nUMBERField = value;
                this.RaisePropertyChanged("NUMBER");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string MESSAGE_V1 {
            get {
                return this.mESSAGE_V1Field;
            }
            set {
                this.mESSAGE_V1Field = value;
                this.RaisePropertyChanged("MESSAGE_V1");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string MESSAGE_V2 {
            get {
                return this.mESSAGE_V2Field;
            }
            set {
                this.mESSAGE_V2Field = value;
                this.RaisePropertyChanged("MESSAGE_V2");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MESSAGE_V3 {
            get {
                return this.mESSAGE_V3Field;
            }
            set {
                this.mESSAGE_V3Field = value;
                this.RaisePropertyChanged("MESSAGE_V3");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string MESSAGE_V4 {
            get {
                return this.mESSAGE_V4Field;
            }
            set {
                this.mESSAGE_V4Field = value;
                this.RaisePropertyChanged("MESSAGE_V4");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string SYSTEM {
            get {
                return this.sYSTEMField;
            }
            set {
                this.sYSTEMField = value;
                this.RaisePropertyChanged("SYSTEM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_LOGIN_CancelarDoctosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SuKarne.com/pi/LOGIN/Cancelar_DoctosContables", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SIE.Services.ServicioPolizasCancelacion.DT_LOGIN_CancelarDoctos_ItemItem[] MT_LOGIN_CacelarDoctos_Req;
        
        public SI_LOGIN_CancelarDoctosRequest() {
        }
        
        public SI_LOGIN_CancelarDoctosRequest(SIE.Services.ServicioPolizasCancelacion.DT_LOGIN_CancelarDoctos_ItemItem[] MT_LOGIN_CacelarDoctos_Req) {
            this.MT_LOGIN_CacelarDoctos_Req = MT_LOGIN_CacelarDoctos_Req;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_LOGIN_CancelarDoctosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SuKarne.com/pi/LOGIN/Cancelar_DoctosContables", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SIE.Services.ServicioPolizasCancelacion.DT_SAP_CancelarDoctos_ResItem[] MT_CancelarDoctos_Resp;
        
        public SI_LOGIN_CancelarDoctosResponse() {
        }
        
        public SI_LOGIN_CancelarDoctosResponse(SIE.Services.ServicioPolizasCancelacion.DT_SAP_CancelarDoctos_ResItem[] MT_CancelarDoctos_Resp) {
            this.MT_CancelarDoctos_Resp = MT_CancelarDoctos_Resp;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_LOGIN_CancelarDoctosChannel : SIE.Services.ServicioPolizasCancelacion.SI_LOGIN_CancelarDoctos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_LOGIN_CancelarDoctosClient : System.ServiceModel.ClientBase<SIE.Services.ServicioPolizasCancelacion.SI_LOGIN_CancelarDoctos>, SIE.Services.ServicioPolizasCancelacion.SI_LOGIN_CancelarDoctos {
        
        public SI_LOGIN_CancelarDoctosClient() {
        }
        
        public SI_LOGIN_CancelarDoctosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_LOGIN_CancelarDoctosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_LOGIN_CancelarDoctosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_LOGIN_CancelarDoctosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SIE.Services.ServicioPolizasCancelacion.SI_LOGIN_CancelarDoctosResponse SIE.Services.ServicioPolizasCancelacion.SI_LOGIN_CancelarDoctos.SI_LOGIN_CancelarDoctos(SIE.Services.ServicioPolizasCancelacion.SI_LOGIN_CancelarDoctosRequest request) {
            return base.Channel.SI_LOGIN_CancelarDoctos(request);
        }
        
        public SIE.Services.ServicioPolizasCancelacion.DT_SAP_CancelarDoctos_ResItem[] SI_LOGIN_CancelarDoctos(SIE.Services.ServicioPolizasCancelacion.DT_LOGIN_CancelarDoctos_ItemItem[] MT_LOGIN_CacelarDoctos_Req) {
            SIE.Services.ServicioPolizasCancelacion.SI_LOGIN_CancelarDoctosRequest inValue = new SIE.Services.ServicioPolizasCancelacion.SI_LOGIN_CancelarDoctosRequest();
            inValue.MT_LOGIN_CacelarDoctos_Req = MT_LOGIN_CacelarDoctos_Req;
            SIE.Services.ServicioPolizasCancelacion.SI_LOGIN_CancelarDoctosResponse retVal = ((SIE.Services.ServicioPolizasCancelacion.SI_LOGIN_CancelarDoctos)(this)).SI_LOGIN_CancelarDoctos(inValue);
            return retVal.MT_CancelarDoctos_Resp;
        }
    }
}
