//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIE.Services.ServicioPolizasLogin {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://SuKarne.com/pi/LOGIN/PolizasContables", ConfigurationName="ServicioPolizasLogin.SI_LOGIN_PolizasContables")]
    public interface SI_LOGIN_PolizasContables {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación SI_LOGIN_PolizasContables no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SIE.Services.ServicioPolizasLogin.SI_LOGIN_PolizasContablesResponse SI_LOGIN_PolizasContables(SIE.Services.ServicioPolizasLogin.SI_LOGIN_PolizasContablesRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://SuKarne.com/pi/LOGIN/PolizasContables")]
    public partial class DT_POLIZA_PERIFERICO_ITEMDatos : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string norefField;
        
        private string fecha_docField;
        
        private string fecha_contField;
        
        private string clase_docField;
        
        private string sociedadField;
        
        private string monedaField;
        
        private string tipocambioField;
        
        private string texto_docField;
        
        private string mesField;
        
        private string cuentaField;
        
        private string proveedorField;
        
        private string clienteField;
        
        private string indica_cmeField;
        
        private string importeField;
        
        private string indica_impField;
        
        private string centro_ctoField;
        
        private string orden_intField;
        
        private string centro_benField;
        
        private string texto_asigField;
        
        private string conceptoField;
        
        private string divisionField;
        
        private string clase_movtField;
        
        private string bus_actField;
        
        private string periodoField;
        
        private string nolineaField;
        
        private string ref1Field;
        
        private string ref2Field;
        
        private string ref3Field;
        
        private string fecha_imtoField;
        
        private string cond_imtoField;
        
        private string clave_imtoField;
        
        private string tipo_retField;
        
        private string cod_retField;
        
        private string imp_retField;
        
        private string imp_ivaField;
        
        private string archifolioField;
        
        private string segmentoField;
        
        private string area_funcField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string noref {
            get {
                return this.norefField;
            }
            set {
                this.norefField = value;
                this.RaisePropertyChanged("noref");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fecha_doc {
            get {
                return this.fecha_docField;
            }
            set {
                this.fecha_docField = value;
                this.RaisePropertyChanged("fecha_doc");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string fecha_cont {
            get {
                return this.fecha_contField;
            }
            set {
                this.fecha_contField = value;
                this.RaisePropertyChanged("fecha_cont");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string clase_doc {
            get {
                return this.clase_docField;
            }
            set {
                this.clase_docField = value;
                this.RaisePropertyChanged("clase_doc");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string sociedad {
            get {
                return this.sociedadField;
            }
            set {
                this.sociedadField = value;
                this.RaisePropertyChanged("sociedad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
                this.RaisePropertyChanged("moneda");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string tipocambio {
            get {
                return this.tipocambioField;
            }
            set {
                this.tipocambioField = value;
                this.RaisePropertyChanged("tipocambio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string texto_doc {
            get {
                return this.texto_docField;
            }
            set {
                this.texto_docField = value;
                this.RaisePropertyChanged("texto_doc");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string mes {
            get {
                return this.mesField;
            }
            set {
                this.mesField = value;
                this.RaisePropertyChanged("mes");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string cuenta {
            get {
                return this.cuentaField;
            }
            set {
                this.cuentaField = value;
                this.RaisePropertyChanged("cuenta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string proveedor {
            get {
                return this.proveedorField;
            }
            set {
                this.proveedorField = value;
                this.RaisePropertyChanged("proveedor");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
                this.RaisePropertyChanged("cliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string indica_cme {
            get {
                return this.indica_cmeField;
            }
            set {
                this.indica_cmeField = value;
                this.RaisePropertyChanged("indica_cme");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string importe {
            get {
                return this.importeField;
            }
            set {
                this.importeField = value;
                this.RaisePropertyChanged("importe");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string indica_imp {
            get {
                return this.indica_impField;
            }
            set {
                this.indica_impField = value;
                this.RaisePropertyChanged("indica_imp");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string centro_cto {
            get {
                return this.centro_ctoField;
            }
            set {
                this.centro_ctoField = value;
                this.RaisePropertyChanged("centro_cto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string orden_int {
            get {
                return this.orden_intField;
            }
            set {
                this.orden_intField = value;
                this.RaisePropertyChanged("orden_int");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string centro_ben {
            get {
                return this.centro_benField;
            }
            set {
                this.centro_benField = value;
                this.RaisePropertyChanged("centro_ben");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string texto_asig {
            get {
                return this.texto_asigField;
            }
            set {
                this.texto_asigField = value;
                this.RaisePropertyChanged("texto_asig");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string concepto {
            get {
                return this.conceptoField;
            }
            set {
                this.conceptoField = value;
                this.RaisePropertyChanged("concepto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string division {
            get {
                return this.divisionField;
            }
            set {
                this.divisionField = value;
                this.RaisePropertyChanged("division");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string clase_movt {
            get {
                return this.clase_movtField;
            }
            set {
                this.clase_movtField = value;
                this.RaisePropertyChanged("clase_movt");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string bus_act {
            get {
                return this.bus_actField;
            }
            set {
                this.bus_actField = value;
                this.RaisePropertyChanged("bus_act");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
                this.RaisePropertyChanged("periodo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string nolinea {
            get {
                return this.nolineaField;
            }
            set {
                this.nolineaField = value;
                this.RaisePropertyChanged("nolinea");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string ref1 {
            get {
                return this.ref1Field;
            }
            set {
                this.ref1Field = value;
                this.RaisePropertyChanged("ref1");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string ref2 {
            get {
                return this.ref2Field;
            }
            set {
                this.ref2Field = value;
                this.RaisePropertyChanged("ref2");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string ref3 {
            get {
                return this.ref3Field;
            }
            set {
                this.ref3Field = value;
                this.RaisePropertyChanged("ref3");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string fecha_imto {
            get {
                return this.fecha_imtoField;
            }
            set {
                this.fecha_imtoField = value;
                this.RaisePropertyChanged("fecha_imto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string cond_imto {
            get {
                return this.cond_imtoField;
            }
            set {
                this.cond_imtoField = value;
                this.RaisePropertyChanged("cond_imto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string clave_imto {
            get {
                return this.clave_imtoField;
            }
            set {
                this.clave_imtoField = value;
                this.RaisePropertyChanged("clave_imto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string tipo_ret {
            get {
                return this.tipo_retField;
            }
            set {
                this.tipo_retField = value;
                this.RaisePropertyChanged("tipo_ret");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string cod_ret {
            get {
                return this.cod_retField;
            }
            set {
                this.cod_retField = value;
                this.RaisePropertyChanged("cod_ret");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string imp_ret {
            get {
                return this.imp_retField;
            }
            set {
                this.imp_retField = value;
                this.RaisePropertyChanged("imp_ret");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string imp_iva {
            get {
                return this.imp_ivaField;
            }
            set {
                this.imp_ivaField = value;
                this.RaisePropertyChanged("imp_iva");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string archifolio {
            get {
                return this.archifolioField;
            }
            set {
                this.archifolioField = value;
                this.RaisePropertyChanged("archifolio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string segmento {
            get {
                return this.segmentoField;
            }
            set {
                this.segmentoField = value;
                this.RaisePropertyChanged("segmento");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public string area_func {
            get {
                return this.area_funcField;
            }
            set {
                this.area_funcField = value;
                this.RaisePropertyChanged("area_func");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://SuKarne.com/pi/LOGIN/PolizasContables")]
    public partial class DT_PolizasContablesResItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tYPEField;
        
        private string idField;
        
        private string nUMBERField;
        
        private string mESSAGEField;
        
        private string mESSAGE_V1Field;
        
        private string mESSAGE_V2Field;
        
        private string mESSAGE_V3Field;
        
        private string mESSAGE_V4Field;
        
        private string sYSTEMField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NUMBER {
            get {
                return this.nUMBERField;
            }
            set {
                this.nUMBERField = value;
                this.RaisePropertyChanged("NUMBER");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string MESSAGE_V1 {
            get {
                return this.mESSAGE_V1Field;
            }
            set {
                this.mESSAGE_V1Field = value;
                this.RaisePropertyChanged("MESSAGE_V1");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string MESSAGE_V2 {
            get {
                return this.mESSAGE_V2Field;
            }
            set {
                this.mESSAGE_V2Field = value;
                this.RaisePropertyChanged("MESSAGE_V2");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MESSAGE_V3 {
            get {
                return this.mESSAGE_V3Field;
            }
            set {
                this.mESSAGE_V3Field = value;
                this.RaisePropertyChanged("MESSAGE_V3");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string MESSAGE_V4 {
            get {
                return this.mESSAGE_V4Field;
            }
            set {
                this.mESSAGE_V4Field = value;
                this.RaisePropertyChanged("MESSAGE_V4");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string SYSTEM {
            get {
                return this.sYSTEMField;
            }
            set {
                this.sYSTEMField = value;
                this.RaisePropertyChanged("SYSTEM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_LOGIN_PolizasContablesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SuKarne.com/pi/LOGIN/PolizasContables", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Datos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SIE.Services.ServicioPolizasLogin.DT_POLIZA_PERIFERICO_ITEMDatos[] MT_POLIZA_PERIFERICO;
        
        public SI_LOGIN_PolizasContablesRequest() {
        }
        
        public SI_LOGIN_PolizasContablesRequest(SIE.Services.ServicioPolizasLogin.DT_POLIZA_PERIFERICO_ITEMDatos[] MT_POLIZA_PERIFERICO) {
            this.MT_POLIZA_PERIFERICO = MT_POLIZA_PERIFERICO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_LOGIN_PolizasContablesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SuKarne.com/pi/LOGIN/PolizasContables", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SIE.Services.ServicioPolizasLogin.DT_PolizasContablesResItem[] MT_PolizasContablesRes;
        
        public SI_LOGIN_PolizasContablesResponse() {
        }
        
        public SI_LOGIN_PolizasContablesResponse(SIE.Services.ServicioPolizasLogin.DT_PolizasContablesResItem[] MT_PolizasContablesRes) {
            this.MT_PolizasContablesRes = MT_PolizasContablesRes;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_LOGIN_PolizasContablesChannel : SIE.Services.ServicioPolizasLogin.SI_LOGIN_PolizasContables, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_LOGIN_PolizasContablesClient : System.ServiceModel.ClientBase<SIE.Services.ServicioPolizasLogin.SI_LOGIN_PolizasContables>, SIE.Services.ServicioPolizasLogin.SI_LOGIN_PolizasContables {
        
        public SI_LOGIN_PolizasContablesClient() {
        }
        
        public SI_LOGIN_PolizasContablesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_LOGIN_PolizasContablesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_LOGIN_PolizasContablesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_LOGIN_PolizasContablesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SIE.Services.ServicioPolizasLogin.SI_LOGIN_PolizasContablesResponse SIE.Services.ServicioPolizasLogin.SI_LOGIN_PolizasContables.SI_LOGIN_PolizasContables(SIE.Services.ServicioPolizasLogin.SI_LOGIN_PolizasContablesRequest request) {
            return base.Channel.SI_LOGIN_PolizasContables(request);
        }
        
        public SIE.Services.ServicioPolizasLogin.DT_PolizasContablesResItem[] SI_LOGIN_PolizasContables(SIE.Services.ServicioPolizasLogin.DT_POLIZA_PERIFERICO_ITEMDatos[] MT_POLIZA_PERIFERICO) {
            SIE.Services.ServicioPolizasLogin.SI_LOGIN_PolizasContablesRequest inValue = new SIE.Services.ServicioPolizasLogin.SI_LOGIN_PolizasContablesRequest();
            inValue.MT_POLIZA_PERIFERICO = MT_POLIZA_PERIFERICO;
            SIE.Services.ServicioPolizasLogin.SI_LOGIN_PolizasContablesResponse retVal = ((SIE.Services.ServicioPolizasLogin.SI_LOGIN_PolizasContables)(this)).SI_LOGIN_PolizasContables(inValue);
            return retVal.MT_PolizasContablesRes;
        }
    }
}
