ALTER TABLE Jaula ADD NumEconomico VARCHAR(10) NOT NULL DEFAULT '';
ALTER TABLE Jaula ADD MarcaID INT NULL;
ALTER TABLE Jaula ADD Modelo INT NOT NULL DEFAULT 0;
ALTER TABLE Jaula ADD Boletinado BIT NULL;
ALTER TABLE Jaula ADD Observaciones VARCHAR(255) NULL;
ALTER TABLE Jaula ALTER COLUMN Capacidad INT NULL;
ALTER TABLE Jaula ALTER COLUMN Secciones INT NULL;

ALTER TABLE [dbo].[Jaula] ADD FOREIGN KEY ([MarcaID]) REFERENCES [dbo].[Marca] ([MarcaID]) ON DELETE NO ACTION ON UPDATE NO ACTION;