ALTER TABLE Camion ADD NumEconomico VARCHAR(10) NOT NULL DEFAULT '';
ALTER TABLE Camion ADD MarcaID INT NULL;
ALTER TABLE Camion ADD Modelo INT NOT NULL DEFAULT 0;
ALTER TABLE Camion ADD Color VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE Camion ADD Boletinado BIT NULL;
ALTER TABLE Camion ADD Observaciones VARCHAR(255) NULL;

ALTER TABLE [dbo].[Camion] ADD FOREIGN KEY ([MarcaID]) REFERENCES [dbo].[Marca] ([MarcaID]) ON DELETE NO ACTION ON UPDATE NO ACTION;