ALTER TABLE Embarque ADD OrganizacionOrigenID INT NULL;
ALTER TABLE Embarque ADD OrganizacionDestinoID INT NULL;
ALTER TABLE Embarque ADD CitaCarga SMALLDATETIME NOT NULL DEFAULT (GETDATE());
ALTER TABLE Embarque ADD HorasTransito INT NULL;
ALTER TABLE Embarque ADD ResponsableEmbarque VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE Embarque ADD CitaDescarga SMALLDATETIME NOT NULL DEFAULT (GETDATE());
ALTER TABLE Embarque ADD ProveedorID INT NULL;
ALTER TABLE Embarque ADD RutaID INT NULL;
ALTER TABLE Embarque ADD Kilometros DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE Embarque ADD DobleTransportista BIT NOT NULL DEFAULT 0;
ALTER TABLE Embarque ADD CamionID INT NULL;
ALTER TABLE Embarque ADD JaulaID INT NULL;
ALTER TABLE Embarque ADD Activo BIT NOT NULL DEFAULT 0;
ALTER TABLE Embarque ADD CONSTRAINT FK_Embarque_OrganizacionOrigen  FOREIGN KEY (OrganizacionOrigenID) REFERENCES Organizacion(OrganizacionID);
ALTER TABLE Embarque ADD CONSTRAINT FK_Embarque_OrganizacionDestino FOREIGN KEY (OrganizacionDestinoID) REFERENCES Organizacion(OrganizacionID);
ALTER TABLE Embarque ADD CONSTRAINT FK_Embarque_Proveedor			FOREIGN KEY (ProveedorID) REFERENCES Proveedor(ProveedorID);
ALTER TABLE Embarque ADD CONSTRAINT FK_Embarque_Ruta                FOREIGN KEY (RutaID) REFERENCES ConfiguracionEmbarqueDetalle(ConfiguracionEmbarqueDetalleID);
ALTER TABLE Embarque ADD CONSTRAINT FK_Embarque_Camion 				FOREIGN KEY (CamionID) REFERENCES Camion(CamionID);
ALTER TABLE Embarque ADD CONSTRAINT FK_Embarque_Jaula				FOREIGN KEY (JaulaID) REFERENCES Jaula(JaulaID);