Insert Into Organizacion (TipoOrganizacionID, Descripcion, Activo, RFC, IvaID, Sociedad, FechaCreacion) VALUES (2, 'GANADERA INTEGRAL VIZUR', 1, '', 3, '212' , GETDATE()) 
Insert Into Organizacion (TipoOrganizacionID, Descripcion, Activo, RFC, IvaID, Sociedad, FechaCreacion) VALUES (2, 'GANADERA INTEGRAL CENTINELA', 1, '', 3, '212' , GETDATE()) 
Insert Into Organizacion (TipoOrganizacionID, Descripcion, Activo, RFC, IvaID, Sociedad, FechaCreacion) VALUES (2, 'GANADERA INTEGRAL SK', 1, '', 3, '212' , GETDATE()) 
Insert Into Organizacion (TipoOrganizacionID, Descripcion, Activo, RFC, IvaID, Sociedad, FechaCreacion) VALUES (2, 'GANADERA INTEGRAL MONARCA', 1, '', 3, '212' , GETDATE()) 
Insert Into Organizacion (TipoOrganizacionID, Descripcion, Activo, RFC, IvaID, Sociedad, FechaCreacion) VALUES (2, 'GANADERA INTEGRAL LUCERO', 1, '', 3, '212' , GETDATE()) 
Insert Into Organizacion (TipoOrganizacionID, Descripcion, Activo, RFC, IvaID, Sociedad, FechaCreacion) VALUES (1, 'CORPORATIVO', 1, '', 3, '212' , GETDATE()) 
Insert Into Organizacion (TipoOrganizacionID, Descripcion, Activo, RFC, IvaID, Sociedad, FechaCreacion) VALUES (3, 'COMPRA DIRECTA RANCHO 1', 1, '', 3, '212' , GETDATE()) 
Insert Into Organizacion (TipoOrganizacionID, Descripcion, Activo, RFC, IvaID, Sociedad, FechaCreacion) VALUES (3, 'COMPRA DIRECTA RANCHO 2', 1, '', 3, '212' , GETDATE()) 
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA EL FUERTE, SIN', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA LOS MOCHIS, SIN', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA SINALOA DE LEYVA, SIN', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA GUASAVE, SIN', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA GUAMUCHIL, SIN', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA PERICOS, SIN', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA PIAXTLA, SIN', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA EL ROSARIO, SIN', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA ESCUINAPA, SIN', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA LA CRUZ, SIN', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA ACAPONETA, NAY', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA EL DORADO, SIN', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA SANTIAGO IXCUINTLA, NAY', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA LAS VARAS, NAY', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA TOMATLAN, JAL', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA CIHUATLAN, JAL', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA GUADALAJARA, JAL', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA LAS PALMAS, JAL', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA COLIMA, COL', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA AHUACATLAN, NAY', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA TEPIC, NAY', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA CALVILLO, AGS', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA CHIHUAHUA, CHIH', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA CUAUHTEMOC, CHIH', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA EL TEUL, ZAC', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA FRESNILLO, ZAC', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA CASAS GRANDES, CHIH', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA YAHUALICA, JAL', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA JEREZ, ZAC', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA GUADALUPE VICTORIA, DGO', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA LA PAZ, BCS', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA DURANGO, DGO', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA SOMBRERETE, ZAC', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA LAS NIEVES, DGO', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA CD CONSTITUCION, BCS', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA RIO GRANDE, ZAC', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA TEOCALTICHE, JAL', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA PAPANTLA, VER', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA PALENQUE, CHIA', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA TANQUIAN, SLP', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA TENOSIQUE, TAB', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA TAMAZULA, JAL', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA TEPATITLAN, JAL', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA RODEO, DGO', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA SABINAS, COAH', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA NAVOJOA, SON', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA MOCTEZUMA, SON', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA TAMUIN, SLP', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA ACAYUCAN, VER', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA ISLA, VER', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA CUAJINICUILAPA, GRO', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA TECPAN, GRO', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA TECALITLAN, JAL', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA HUIMANGUILLO, TAB', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA MACUSPANA, TAB', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA TENAMAXTLAN, JAL', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA TALPA DE ALLENDE, JAL', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA COYUCA DE BENITEZ, GRO', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA CRUZ GRANDE, GRO', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA MAPASTEPEC, CHIA', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA EL GRULLO, JAL', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA JAMILTEPEC, OAX', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA AMATITAN, JAL', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA LAS CHOAPAS, VER', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA MATIAS ROMERO, OAX', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA CAMARGO, CHIH', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA TUXPAN, VER', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA SANTA MARIA DEL ORO, DGO', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA TANTOYUCA, VER', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA ARRIAGA, CHIA', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA PLAYA VICENTE, VER', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA OCOSINGO, CHIA', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA PICHUCALCO, CHIA', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA LA VENTOSA, OAX', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA JONUTA, TAB', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA COPAINALA, CHIA', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA CANDELARIA, CAM', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA ESCARCEGA, CAM', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA TLALIXCOYAN, VER', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA TIERRA BLANCA, VER', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA ALDAMA, TAM', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA OZULUAMA, VER', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA PICH, CAM', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA ANGEL R CABADAS, VER', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA EL HIGO, VER', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA BALANCAN, TAB', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA LOPEZ MATEOS, CAM', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA TAMASOPO, SLP', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA CHICONTEPEC, VER', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA VILLAFLORES, CHIA', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA CINTALAPA, CHIA', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA MALPASO, CHIA', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA PIJIJIAPAN, CHIA', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA HERMOSILLO, SON', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA PARRAL, CHIH', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA SALTO DE AGUA, CHIA', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA VILLA HIDALGO, NAY', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA NAVOLATO, SIN', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA CHOIX, SIN', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA MAZATLAN, SIN', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA SANTA ELENA, VER', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA LOS RAMONES, NL', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA EMILIO CARRANZA, VER', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA CATEMACO, VER', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA RIO GRANDE, OAX', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA LOMA BONITA, OAX', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA JESUS CARRANZA, VER', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA SAN MARTIN, SLP', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA IXTLAHUACAN DEL RIO, JAL', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA SANTIAGO PAPASQUIARO, DGO', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA PALMAS DE ABAJO, VER', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA MAGDALENA, JAL', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA EBANO, SLP', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA TECOMAN, COL', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA OCOZOCOAUTLA, CHIA', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA PALIZADA, CAM', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA ARANDAS, JAL', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA MADERA, CHIH', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA CHAMPOTON, CAM', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA SABANCUY, CAM', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA JALPA DE MENDEZ, TAB', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA TACOTALPA, TAB', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA BAHIA DE BANDERAS, NAY', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA VILLANUEVA, ZAC', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA LAGOS DE MORENO, JAL', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA VALPARAISO, ZAC', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA BUENAVENTURA, CHIH', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA NARANJOS, VER', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA TAPACHULA, CHIA', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA COCULA, GRO', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA LUVIANOS, MEX', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA VILLA PURIFICACION, JAL', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA FRONTERA, TAB', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA COMALCALCO, TAB', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA MEZQUITAL, DGO', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA CUATRO CIENEGAS, COAH', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA NAMIQUIPA, CHIH', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA BERMEJILLO, DGO', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA JUAREZ, CHIA', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA TATAHUICAPAN, VER', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA OJITLAN, OAX', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA LA CHINANTLA, VER', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA MANO MARQUEZ, OAX', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA MARIA LOMBARDO, OAX', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA VALLE NACIONAL, OAX', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA AGUASCALIENTES, AGS', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA SANTA MARIA CORTIJA, OAX', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA CANATLAN, DGO', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA CERRO DEL NANCHITAL, VER', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA CORRAL NUEVO, VER', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (4, 'CA TUXCUECA, JAL', '', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA LUIS MEDINA AMADOR, VER', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA RODRIGO MEDINA, VER', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA ANA LILIA MUNDO, VER', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA SERGIO RAMIREZ, CHIS', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'AGROINDUSTRIAS MEDINA SPR DE RL, SAN ELPIDIO', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA CONCEPCION SANCHEZ, VER', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'AGROINDUSTRIAS MEDINA SPR DE RL, OKLAHOMA', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA SAN FERNANDO, MXL', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA CELIA AGUIRRE, VERACRUZ', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA DIOSDADO VAZQUEZ', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA ROGELIO FIGUEROA / ASALIA GALVAN', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA VENTURA MARIN DIAZ', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA JOAQUIN FOSTER ZEBADUA, CHPAS.', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA MARCOS GUTIERREZ, CHPAS', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA MANZUR CRUZ, EL PORVENIR', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA MANZUR CRUZ, SANTA BÁRBARA', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA GUADALUPE SALAZAR VARGAS, VER', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA ALBERTO MARIN AGUILERA, CHPAS', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA ANA CRISTINA RUIZ COUTIÑO, CHPAS', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA GERARDO ARELLANO JIMENEZ, VER', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA CARMEN NEMES, CHIAPAS', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA LUIS GOMEZ, TAB', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA AGUSTIN DOMINGEZ, CHPAS', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA GABRIEL TORRES, VER', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA IGNACIO SUAZO', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA PABLO MARTELL SANTOS', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA MIGUEL ANGEL LANDEROS BARRETO, CHIAPAS', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA MARIA MARLENE BERNAL JAIMES', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA  RUIZ ESPONDA SPR DE RL (CHIAPAS)', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA JOSE BENJAMIN BAEZ RANERO', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA CARLOS LOPEZ HARO', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA EZEQUIEL ROSAS DELFIN', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA RAFAEL HUMBERTO SPINOSO PORTILLA', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA ROSA YOLANDA DEL RIVERO LASTRA', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA RAFAEL ZARCO MOLLINEDO', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA GANADERIA ITSMAL SPR DE RL', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'ROBERTO CARLOS CASTILLO CABRERA', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA ALVARES ACOSTA GANADERIA SPR DE RL', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA MANUEL ROMAN OCAMPO ARGAEZ', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA ORBELIN CRUZ CASTELLANOS', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA EMILIO FERRAO RODRIGUEZ', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA GRUPO AGRO INDUSTRIAL ARIAS SA DE CV', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA MANUEL SANCHEZ CRUZ', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA GUSTAVO ADOLFO MANZANILLA LOZANO', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA ALDO ANTONIO MORALES OLAN', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA RAUL PRIOR CUERVO', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA  MATILDE GUADALUPE SUAREZ OLVERA', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA GRUPO LOS CHOCOYOS S DE PR DE RL', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA LECHERIA J. MARIO ROSADO SPR DE RL', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA JOSE A. CRESPO MEDINA (TAMUIN)', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA LUIS MEDINA AGUIRRE', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA JESUS ROLDAN SERNA (VERACRUZ)', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA RUIZ ESPONDA SPR DE RL  (BENEMERITO)', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA JOSE A CRESPO MEDINA (TANCANHUITZ)', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA HECTOR MANUEL AGUIRRE PEREZ', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA J. CARMEN BARAJAS MERAZ', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA GRACIELA MARIEL MORAN', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA OCTAVIO ROJAS JONGUITUD', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA RECESVINTO ZUÑIGA FLORES', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA ARMANDO BARRADAS SUAREZ', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA GRAG SPR DE RL', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA JOSE LUIS ROMERO DOMINGUEZ', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA RENE TREJO DEL ANGEL', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (5, 'PRADERA JOSÉ MANUEL PORTILLA GONZALEZ', ' ', 3, 1, '212' , GETDATE())
Insert Into Organizacion (TipoOrganizacionID, Descripcion, Activo, RFC, IvaID, Sociedad, FechaCreacion) VALUES (6, 'DESCANSO PASO DEL TORO', 1, '', 3, '212' , GETDATE()) 
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (7, 'CADIS NAYARIT', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (7, 'CADIS Acayucan, VER', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (7, 'SEMENTALES Culiacan', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (7, 'CADIS Naranjos, VER', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (7, 'CADIS Macuspana, TAB', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (7, 'SEMENTALES Monterrey', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (7, 'CADIS Santa Elena', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (7, 'CADIS Huasteca', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (7, 'CADIS Escarcega', ' ', 3, 1, '212' , GETDATE())
INSERT INTO Organizacion (TipoOrganizacionID, Descripcion, RFC, IvaID, Activo, Sociedad, FechaCreacion) VALUES (7, 'CADIS Ocozocoautla', ' ', 3, 1, '212' , GETDATE())
Insert Into Organizacion (TipoOrganizacionID, Descripcion, Activo, RFC, IvaID, Sociedad, FechaCreacion) VALUES (8, 'GANADO INTENSIVO PROVEEDOR 1', 1, '', 3, '212' , GETDATE()) 
Insert Into Organizacion (TipoOrganizacionID, Descripcion, Activo, RFC, IvaID, Sociedad, FechaCreacion) VALUES (8, 'GANADO INTENSIVO PROVEEDOR 2', 1, '', 3, '212' , GETDATE()) 