INSERT INTO TipoFolio (Descripcion) VALUES ('Programación Embarque')
INSERT INTO TipoFolio (Descripcion) VALUES ('Entrada Ganado')
INSERT INTO TipoFolio (Descripcion) VALUES ('Lote')
INSERT INTO TipoFolio (Descripcion) VALUES ('Evaluación Partida')
INSERT INTO TipoFolio (Descripcion) VALUES ('Orden Sacrificio')
INSERT INTO TipoFolio (Descripcion) VALUES ('Salida Individual Venta')
INSERT INTO TipoFolio (Descripcion) VALUES ('Salida Ganado')
INSERT INTO TipoFolio (Descripcion) VALUES ('Contrato')
INSERT INTO TipoFolio (Descripcion) VALUES ('Entrada Producto')
INSERT INTO TipoFolio (Descripcion) VALUES ('Vigilancia')
INSERT INTO TipoFolio (Descripcion) VALUES ('Solicitud Almacen')
INSERT INTO TipoFolio (Descripcion) VALUES ('Salida Venta Traspaso')
INSERT INTO TipoFolio (Descripcion) VALUES ('Solicitud Materia Prima')
INSERT INTO TipoFolio (Descripcion) VALUES ('Gasto al Inventario')
INSERT INTO TipoFolio (Descripcion) VALUES ('Recepción Producto')
INSERT INTO TipoFolio (Descripcion) VALUES ('Salida Por Muerte')
INSERT INTO TipoFolio (Descripcion) VALUES ('Produccion Formula')
INSERT INTO TipoFolio (Descripcion) VALUES ('Gastos Materia Prima')