INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,1,1)	
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,2,1)	
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,3,1)	
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,4,1)	
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,5,1)	
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,6,1)	
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,7,1)	
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,8,1)	
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,9,1)	
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,10,1)	
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,11,1)	
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,12,1)	
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,13,1)	
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,14,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,15,1)		
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,16,1)	
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,17,1)	
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,18,1)	
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,19,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,20,1)	
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,21,1)	
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,22,1)	
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,23,1)	
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,24,1)	
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,25,1)	
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,26,1)	
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,27,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,28,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,29,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,30,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,31,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,32,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,33,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,34,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,35,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,36,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,37,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,38,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,39,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,40,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,41,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,42,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,43,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,44,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,45,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,46,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,47,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,48,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,49,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,50,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,51,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,52,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,53,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,54,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,55,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,56,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,57,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,58,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,59,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,60,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,61,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,62,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,63,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,64,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,65,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,66,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,67,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,68,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,69,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,70,1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1,71,1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 72, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 73, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 74, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 75, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 76, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 77, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 78, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 79, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 80, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 81, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 82, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 83, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 84, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 85, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 86, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 87, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 88, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 89, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 90, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 91, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 92, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 93, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 94, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 95, 1)

INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 96, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 97, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 98, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 99, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 100, 1)

INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 101, 1)


INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 102, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 103, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 104, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 105, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 106, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 107, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 108, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 109, 1)

INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 110, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 111, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 112, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 113, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 114, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 115, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 116, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 117, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 118, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 119, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 120, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 121, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 122, 1)

------------------Insert para registro de permisos de piloto ------------------
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (2, 11, 1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (2, 12, 1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (2, 13, 1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (3, 5,	1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (3, 6,	1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (3, 7,	1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (3, 8,	1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (3, 9,	1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (3, 10, 1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (3, 14, 1)

INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1, 120, 1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1, 121, 1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1, 122, 1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1, 123, 1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1, 124, 1)
--Recepción Materia Prima
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1, 126, 1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1, 127, 1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1, 128, 1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1, 129, 1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1, 130, 1)
INSERT INTO GrupoFormulario (GrupoID, FormularioID, AccesoID) VALUES (1, 131, 1)
--Planta de Alimentos
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 132, 1)

--Administración
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 133, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 134, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 135, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 136, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 137, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 138, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 139, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 140, 1)

INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 141, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 142, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 143, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 144, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 145, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 146, 1)

--Almacen
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 147, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 148, 1)

--Administración
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 149, 1)

--Calidad	
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 150, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 151, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 152, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 153, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 154, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 155, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 156, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 158, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 159, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 160, 1)

--Sanidad
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 161, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 162, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 163, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 164, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 165, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 166, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 167, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 168, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 169, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 170, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 171, 1)
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 172, 1)

INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 227, 1)

INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 222, 1)
--Reporte
INSERT INTO GrupoFormulario(GrupoID, FormularioID, AccesoID) VALUES(1, 173, 1)