INSERT INTO TipoProveedor (Descripcion,CodigoGrupoSAP,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('Comisionistas','ZCOM',1,GETDATE(),1)
INSERT INTO TipoProveedor (Descripcion,CodigoGrupoSAP,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('Proveedores Fletes','ZFLE',1,GETDATE(),1)
INSERT INTO TipoProveedor (Descripcion,CodigoGrupoSAP,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('Honorarios','ZHON',1,GETDATE(),1)
INSERT INTO TipoProveedor (Descripcion,CodigoGrupoSAP,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('Proveedores De Ganado','ZPGA',1,GETDATE(),1)
INSERT INTO TipoProveedor (Descripcion,CodigoGrupoSAP,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('Proveedores De Materia Prima','ZPMP',1,GETDATE(),1)