INSERT INTO Rol (Descripcion, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('Jefe de manejo', 1, Getdate(), 1)
INSERT INTO Rol (Descripcion, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('Detector', 1, Getdate(), 1)
INSERT INTO Rol (Descripcion, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('Implantador', 1, Getdate(), 1)
INSERT INTO Rol (Descripcion, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('Vaquero Recepcion', 1, Getdate(), 1)
INSERT INTO Rol (Descripcion, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('Supervisor Sanidad', 1, Getdate(), 1)
INSERT INTO Rol (Descripcion, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('Supervisor Manejo', 1, Getdate(), 1)
INSERT INTO Rol (Descripcion, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('Jefe Sanidad', 1, Getdate(), 1)
INSERT INTO Rol (Descripcion, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('Vaquero', 1, Getdate(), 1)
INSERT INTO Rol (Descripcion, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('Evaluador', 1, Getdate(), 1)
INSERT INTO Rol (Descripcion, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('Basculista', 1, Getdate(), 1)
INSERT INTO rol (descripcion, activo, fechacreacion, usuariocreacionid) VALUES ('Encargado Necropsia', 1, getdate(), 1)
INSERT INTO rol (descripcion, activo, fechacreacion, usuariocreacionid) VALUES ('Recolector', 1, getdate(), 1)
INSERT INTO rol (descripcion, activo, fechacreacion, usuariocreacionid) VALUES ('Supervisor Planta de Alimentos', 1, getdate(), 1)
INSERT INTO rol (descripcion, activo, fechacreacion, usuariocreacionid) VALUES ('Analista', 1, getdate(), 1)
INSERT INTO rol (descripcion, activo, fechacreacion, usuariocreacionid) VALUES ('Mezclador', 1, getdate(), 1)
INSERT INTO rol (descripcion, activo, fechacreacion, usuariocreacionid) VALUES ('Autorizador', 1, getdate(), 1)


