INSERT INTO Condicion (Descripcion, Activo, FechaCreacion, UsuarioCreacionID)
VALUES ('Todo bien', 1, Getdate(), 1)
INSERT INTO Condicion (Descripcion, Activo, FechaCreacion, UsuarioCreacionID)
VALUES ('Quebrado', 1, Getdate(), 1)
INSERT INTO Condicion (Descripcion, Activo, FechaCreacion, UsuarioCreacionID)
VALUES ('Muerto', 1, Getdate(), 1)
INSERT INTO Condicion (Descripcion, Activo, FechaCreacion, UsuarioCreacionID)
VALUES ('Golpeado', 1, Getdate(), 1)
INSERT INTO Condicion (Descripcion, Activo, FechaCreacion, UsuarioCreacionID)
VALUES ('Rechazado', 1, Getdate(), 1)