INSERT INTO TipoGanado (Descripcion,Sexo,PesoMinimo,PesoMaximo,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('Becerro Liviano','M',1,175,1,GETDATE(),1)
INSERT INTO TipoGanado (Descripcion,Sexo,PesoMinimo,PesoMaximo,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('Becerro','M',176,225,1,GETDATE(),1)
INSERT INTO TipoGanado (Descripcion,Sexo,PesoMinimo,PesoMaximo,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('Torete','M',226,300,1,GETDATE(),1)
INSERT INTO TipoGanado (Descripcion,Sexo,PesoMinimo,PesoMaximo,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('Macho Pesado 1','M',301,360,1,GETDATE(),1)
INSERT INTO TipoGanado (Descripcion,Sexo,PesoMinimo,PesoMaximo,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('Macho Pesado 2','M',361,999,1,GETDATE(),1)
INSERT INTO TipoGanado (Descripcion,Sexo,PesoMinimo,PesoMaximo,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('Becerra Liviana','H',1,175,1,GETDATE(),1)
INSERT INTO TipoGanado (Descripcion,Sexo,PesoMinimo,PesoMaximo,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('Becerra','H',176,225,1,GETDATE(),1)
INSERT INTO TipoGanado (Descripcion,Sexo,PesoMinimo,PesoMaximo,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('Vaquilla','H',226,280,1,GETDATE(),1)
INSERT INTO TipoGanado (Descripcion,Sexo,PesoMinimo,PesoMaximo,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('Hembra Pesada 1','H',281,319,1,GETDATE(),1)
INSERT INTO TipoGanado (Descripcion,Sexo,PesoMinimo,PesoMaximo,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('Hembra Pesada 2','H',320,999,1,GETDATE(),1)