INSERT INTO CalidadGanado (Descripcion,Calidad,Sexo,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('EUROPEO','1', 'M', 1, GETDATE(),1)
INSERT INTO CalidadGanado (Descripcion,Calidad,Sexo,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('EUROPEO CON ENCASTE DE CEBU','1.5', 'M', 1, GETDATE(),1)
INSERT INTO CalidadGanado (Descripcion,Calidad,Sexo,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('CEBU','2', 'M', 1, GETDATE(),1)
INSERT INTO CalidadGanado (Descripcion,Calidad,Sexo,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('REGULAR','3', 'M', 1, GETDATE(),1)
INSERT INTO CalidadGanado (Descripcion,Calidad,Sexo,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('VAQUILLA TIPO 2 O TORETE TIPO 2 (OK)','3.5', 'M', 1, GETDATE(),1)
INSERT INTO CalidadGanado (Descripcion,Calidad,Sexo,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('LIVIANO (<180 KGS) POSIBLE PUNTA CHICA','3.5L', 'M', 1, GETDATE(),1)
INSERT INTO CalidadGanado (Descripcion,Calidad,Sexo,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('PESADO JOVEN (>310 KGS) POSIBLE PUNTA GDE','3.5P', 'M', 1, GETDATE(),1)
INSERT INTO CalidadGanado (Descripcion,Calidad,Sexo,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('MADURO','3.5VT2', 'M', 1, GETDATE(),1)
INSERT INTO CalidadGanado (Descripcion,Calidad,Sexo,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('PRE-ENGORDADO (CORRAL O PRADERA)','3.5 PR', 'M', 1, GETDATE(),1)
INSERT INTO CalidadGanado (Descripcion,Calidad,Sexo,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('CORRIENTE: (DEGENERADO, ALEPADO)','4', 'M', 1, GETDATE(),1)
INSERT INTO CalidadGanado (Descripcion,Calidad,Sexo,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('VIEJO O MAS DE 4 PALETAS  (TORO O VACA)','5', 'M', 1, GETDATE(),1)
INSERT INTO CalidadGanado (Descripcion,Calidad,Sexo,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('LECHERO','6', 'M', 1, GETDATE(),1)
INSERT INTO CalidadGanado (Descripcion,Calidad,Sexo,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('CRONICO','7', 'M', 1, GETDATE(),1)
INSERT INTO CalidadGanado (Descripcion,Calidad,Sexo,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('EUROPEO','1', 'H', 1, GETDATE(),1)
INSERT INTO CalidadGanado (Descripcion,Calidad,Sexo,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('EUROPEO CON ENCASTE DE CEBU','1.5', 'H', 1, GETDATE(),1)
INSERT INTO CalidadGanado (Descripcion,Calidad,Sexo,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('CEBU','2', 'H', 1, GETDATE(),1)
INSERT INTO CalidadGanado (Descripcion,Calidad,Sexo,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('REGULAR','3', 'H', 1, GETDATE(),1)
INSERT INTO CalidadGanado (Descripcion,Calidad,Sexo,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('VAQUILLA TIPO 2 O TORETE TIPO 2 (OK)','3.5', 'H', 1, GETDATE(),1)
INSERT INTO CalidadGanado (Descripcion,Calidad,Sexo,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('LIVIANO (<180 KGS) POSIBLE PUNTA CHICA','3.5L', 'H', 1, GETDATE(),1)
INSERT INTO CalidadGanado (Descripcion,Calidad,Sexo,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('PESADO JOVEN (>310 KGS) POSIBLE PUNTA GDE','3.5P', 'H', 1, GETDATE(),1)
INSERT INTO CalidadGanado (Descripcion,Calidad,Sexo,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('MADURO','3.5VT2', 'H', 1, GETDATE(),1)
INSERT INTO CalidadGanado (Descripcion,Calidad,Sexo,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('PRE-ENGORDADO (CORRAL O PRADERA)','3.5 PR', 'H', 1, GETDATE(),1)
INSERT INTO CalidadGanado (Descripcion,Calidad,Sexo,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('CORRIENTE: (DEGENERADO, ALEPADO)','4', 'H', 1, GETDATE(),1)
INSERT INTO CalidadGanado (Descripcion,Calidad,Sexo,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('VIEJO O MAS DE 4 PALETAS  (TORO O VACA)','5', 'H', 1, GETDATE(),1)
INSERT INTO CalidadGanado (Descripcion,Calidad,Sexo,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('LECHERO','6', 'H', 1, GETDATE(),1)
INSERT INTO CalidadGanado (Descripcion,Calidad,Sexo,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('CRONICO','7', 'H', 1, GETDATE(),1)
