INSERT INTO CausaRechazo (Descripcion,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('Liviano',1,GETDATE(),1)
INSERT INTO CausaRechazo (Descripcion,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('Pesado',1,GETDATE(),1)
INSERT INTO CausaRechazo (Descripcion,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('Maduro o Sazon',1,GETDATE(),1)
INSERT INTO CausaRechazo (Descripcion,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('Herniado',1,GETDATE(),1)
INSERT INTO CausaRechazo (Descripcion,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('Pintos',1,GETDATE(),1)
INSERT INTO CausaRechazo (Descripcion,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('Corriente',1,GETDATE(),1)
INSERT INTO CausaRechazo (Descripcion,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('Ceguera',1,GETDATE(),1)
INSERT INTO CausaRechazo (Descripcion,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('Papilomas',1,GETDATE(),1)
INSERT INTO CausaRechazo (Descripcion,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('Rengo',1,GETDATE(),1)
INSERT INTO CausaRechazo (Descripcion,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('Degenerado',1,GETDATE(),1)
INSERT INTO CausaRechazo (Descripcion,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('Cronico Venta',1,GETDATE(),1)
INSERT INTO CausaRechazo (Descripcion,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('Muerto En Transito',1,GETDATE(),1)
INSERT INTO CausaRechazo (Descripcion,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('Traumatismo Transporte',1,GETDATE(),1)
INSERT INTO CausaRechazo (Descripcion,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('Laminitis',1,GETDATE(),1)
INSERT INTO CausaRechazo (Descripcion,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('Abscesos',1,GETDATE(),1)
INSERT INTO CausaRechazo (Descripcion,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('Alepado',1,GETDATE(),1)
INSERT INTO CausaRechazo (Descripcion,Activo,FechaCreacion,UsuarioCreacionID) VALUES ('Sustancias Prohibidas',1,GETDATE(),1)