INSERT INTO Chofer (Nombre, ApellidoPaterno, ApellidoMaterno, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('JOSE DE JESUS', 'RDZ', 'CARDONA',1, GETDATE(), 1)
INSERT INTO Chofer (Nombre, ApellidoPaterno, ApellidoMaterno, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('HUMBERTO', 'DIAZ', 'DELGADO',1, GETDATE(), 1)
INSERT INTO Chofer (Nombre, ApellidoPaterno, ApellidoMaterno, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('ALFREDO', 'ORTIZ', 'MORENO',1, GETDATE(), 1)
INSERT INTO Chofer (Nombre, ApellidoPaterno, ApellidoMaterno, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('JUAN ANTONIO', 'GALLEGOS', '',1, GETDATE(), 1)
INSERT INTO Chofer (Nombre, ApellidoPaterno, ApellidoMaterno, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('LORENZO', 'JUAREZ', 'CERVANTEZ',1, GETDATE(), 1)
INSERT INTO Chofer (Nombre, ApellidoPaterno, ApellidoMaterno, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('RODRIGO', 'LOZANO', 'VILLARREAL',1, GETDATE(), 1)
INSERT INTO Chofer (Nombre, ApellidoPaterno, ApellidoMaterno, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('SERGIO ALFREDO', 'VELASCO', 'ALVARADO',1, GETDATE(), 1)
INSERT INTO Chofer (Nombre, ApellidoPaterno, ApellidoMaterno, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('FERNANDO', 'DELGADO', 'JUAREZ',1, GETDATE(), 1)
INSERT INTO Chofer (Nombre, ApellidoPaterno, ApellidoMaterno, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('ALEJANDRO', 'RODRIGUEZ', 'SANCHEZ',1, GETDATE(), 1)
INSERT INTO Chofer (Nombre, ApellidoPaterno, ApellidoMaterno, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('ROBERTO CARLOS', 'VARGAS', 'AVILA',1, GETDATE(), 1)
INSERT INTO Chofer (Nombre, ApellidoPaterno, ApellidoMaterno, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('JUAN CARLOS', 'JUAREZ', 'GONZALEZ',1, GETDATE(), 1)
INSERT INTO Chofer (Nombre, ApellidoPaterno, ApellidoMaterno, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('ADAN', 'HERNANDEZ', 'OLIVARES',1, GETDATE(), 1)
INSERT INTO Chofer (Nombre, ApellidoPaterno, ApellidoMaterno, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('JUAN DIEGO', 'ZACARIAS', 'ALVAREZ',1, GETDATE(), 1)
INSERT INTO Chofer (Nombre, ApellidoPaterno, ApellidoMaterno, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('BENJAMIN', 'MARQUEZ', 'ENRIQUEZ',1, GETDATE(), 1)
INSERT INTO Chofer (Nombre, ApellidoPaterno, ApellidoMaterno, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('BENITO', 'JUAREZ', 'CERVANTES',1, GETDATE(), 1)
INSERT INTO Chofer (Nombre, ApellidoPaterno, ApellidoMaterno, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('RAMIRO', 'DIAZ', 'DELGADO',1, GETDATE(), 1)
INSERT INTO Chofer (Nombre, ApellidoPaterno, ApellidoMaterno, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('J JESUS', 'RODRIGUEZ', 'MARTINEZ',1, GETDATE(), 1)
INSERT INTO Chofer (Nombre, ApellidoPaterno, ApellidoMaterno, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('MARTIN', 'URZUA', 'HINOJO',1, GETDATE(), 1)
INSERT INTO Chofer (Nombre, ApellidoPaterno, ApellidoMaterno, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('JUAN ANTONIO', 'LOPEZ', 'GLADIN',1, GETDATE(), 1)
INSERT INTO Chofer (Nombre, ApellidoPaterno, ApellidoMaterno, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('MIGUEL', 'DE LA RIVA', 'ACOSTA',1, GETDATE(), 1)
INSERT INTO Chofer (Nombre, ApellidoPaterno, ApellidoMaterno, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('J REFUGIO', 'SANCHEZ', 'MEDINA',1, GETDATE(), 1)
INSERT INTO Chofer (Nombre, ApellidoPaterno, ApellidoMaterno, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('ELISEO', 'CARREON', 'JUAREZ',1, GETDATE(), 1)
INSERT INTO Chofer (Nombre, ApellidoPaterno, ApellidoMaterno, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('RUBEN', 'GUEVARA', 'ACOSTA',1, GETDATE(), 1)
INSERT INTO Chofer (Nombre, ApellidoPaterno, ApellidoMaterno, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('JUAN MIGUEL', 'DE LA RIVA', '',1, GETDATE(), 1)
INSERT INTO Chofer (Nombre, ApellidoPaterno, ApellidoMaterno, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('ADRIAN', 'ORTIZ', 'MORENO',1, GETDATE(), 1)
INSERT INTO Chofer (Nombre, ApellidoPaterno, ApellidoMaterno, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('ELISEO', 'CUELLAR', 'GONZALEZ',1, GETDATE(), 1)
INSERT INTO Chofer (Nombre, ApellidoPaterno, ApellidoMaterno, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('FRANCISCO', 'MUÑOZ', 'MARTINEZ',1, GETDATE(), 1)
INSERT INTO Chofer (Nombre, ApellidoPaterno, ApellidoMaterno, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('SERGIO', 'NAVARRO', 'TORRES',1, GETDATE(), 1)
INSERT INTO Chofer (Nombre, ApellidoPaterno, ApellidoMaterno, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('JORGE', 'REYES', 'ARANDA',1, GETDATE(), 1)
INSERT INTO Chofer (Nombre, ApellidoPaterno, ApellidoMaterno, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('ANTONIO', 'GALLEGOS', 'LOPEZ',1, GETDATE(), 1)
INSERT INTO Chofer (Nombre, ApellidoPaterno, ApellidoMaterno, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('OCTAVIO', 'ZACARIAS', 'ALVAREZ',1, GETDATE(), 1)
INSERT INTO Chofer (Nombre, ApellidoPaterno, ApellidoMaterno, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('JOSE', 'ZACARIAZ', 'ORTIZ',1, GETDATE(), 1)
INSERT INTO Chofer (Nombre, ApellidoPaterno, ApellidoMaterno, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('ISMAEL', 'ARANDA', 'DE LUNA',1, GETDATE(), 1)
INSERT INTO Chofer (Nombre, ApellidoPaterno, ApellidoMaterno, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('DANIEL', 'GARCIA', 'VAZQUEZ',1, GETDATE(), 1)
INSERT INTO Chofer (Nombre, ApellidoPaterno, ApellidoMaterno, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('MARIO', 'GUTIERREZ', 'ARANDA',1, GETDATE(), 1)
INSERT INTO Chofer (Nombre, ApellidoPaterno, ApellidoMaterno, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('JOSE HUMBERTO', 'REYES', 'GOMEZ',1, GETDATE(), 1)
INSERT INTO Chofer (Nombre, ApellidoPaterno, ApellidoMaterno, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('RICARDO', 'JUAREZ', 'GONZALEZ',1, GETDATE(), 1)
INSERT INTO Chofer (Nombre, ApellidoPaterno, ApellidoMaterno, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('JOSE LUIS', 'PEREZ', 'SOLIS',1, GETDATE(), 1)
INSERT INTO Chofer (Nombre, ApellidoPaterno, ApellidoMaterno, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('VICTOR MANUEL', 'JUAREZ', 'CERVANTES',1, GETDATE(), 1)
INSERT INTO Chofer (Nombre, ApellidoPaterno, ApellidoMaterno, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('ADRIAN', 'GONZALEZ', 'MONTES',1, GETDATE(), 1)
INSERT INTO Chofer (Nombre, ApellidoPaterno, ApellidoMaterno, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('TOMAS FERNANDO', 'GUTIERREZ', 'TORRES',1, GETDATE(), 1)
INSERT INTO Chofer (Nombre, ApellidoPaterno, ApellidoMaterno, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('ISMAEL', 'LUNA', 'DE LA CRUZ',1, GETDATE(), 1)
INSERT INTO Chofer (Nombre, ApellidoPaterno, ApellidoMaterno, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('JOSE MANUEL', 'MORENO', 'RODRIGUEZ',1, GETDATE(), 1)
INSERT INTO Chofer (Nombre, ApellidoPaterno, ApellidoMaterno, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('LUIS ANTONIO', 'JUAREZ', 'RUVALCABA',1, GETDATE(), 1)
