insert INTO Costo (ClaveContable,Descripcion,TipoCostoID,TipoProrrateoID,Activo,AbonoA,UsuarioCreacionID,FechaCreacion) values ('001','Costo De Ganado',1,2,1,'AMBOS',1,GETDATE())
insert INTO Costo (ClaveContable,Descripcion,TipoCostoID,TipoProrrateoID,Activo,AbonoA,UsuarioCreacionID,FechaCreacion) values ('002','Alimento',2,3,1,'CUENTA',1,GETDATE())
insert INTO Costo (ClaveContable,Descripcion,TipoCostoID,TipoProrrateoID,Activo,AbonoA,UsuarioCreacionID,FechaCreacion) values ('003','Comision',7,2,1,'PROVEEDOR',1,GETDATE())
insert INTO Costo (ClaveContable,Descripcion,TipoCostoID,TipoProrrateoID,Activo,AbonoA,UsuarioCreacionID,FechaCreacion) values ('004','Fletes',4,2,1,'PROVEEDOR',1,GETDATE())
insert INTO Costo (ClaveContable,Descripcion,TipoCostoID,TipoProrrateoID,Activo,AbonoA,UsuarioCreacionID,FechaCreacion) values ('005','Impuesto Predial',7,4,1,'AMBOS',1,GETDATE())
insert INTO Costo (ClaveContable,Descripcion,TipoCostoID,TipoProrrateoID,Activo,AbonoA,UsuarioCreacionID,FechaCreacion) values ('006','Guias De Transito',7,4,1,'CUENTA',1,GETDATE())
insert INTO Costo (ClaveContable,Descripcion,TipoCostoID,TipoProrrateoID,Activo,AbonoA,UsuarioCreacionID,FechaCreacion) values ('007','Pruebas TB Y BR',7,4,1,'CUENTA',1,GETDATE())
insert INTO Costo (ClaveContable,Descripcion,TipoCostoID,TipoProrrateoID,Activo,AbonoA,UsuarioCreacionID,FechaCreacion) values ('008','Gastos Indirectos',4,2,1,'PROVEEDOR',1,GETDATE())
insert INTO Costo (ClaveContable,Descripcion,TipoCostoID,TipoProrrateoID,Activo,AbonoA,UsuarioCreacionID,FechaCreacion) values ('009','Gastos Engorda Fijos',6,5,1,'CUENTA',1,GETDATE())
insert INTO Costo (ClaveContable,Descripcion,TipoCostoID,TipoProrrateoID,Activo,AbonoA,UsuarioCreacionID,FechaCreacion) values ('010','Gastos Planta Alimento Fijos',6,3,1,'CUENTA',1,GETDATE())
insert INTO Costo (ClaveContable,Descripcion,TipoCostoID,TipoProrrateoID,Activo,AbonoA,UsuarioCreacionID,FechaCreacion) values ('011','Gastos Financieros',6,1,1,'CUENTA',1,GETDATE())
insert INTO Costo (ClaveContable,Descripcion,TipoCostoID,TipoProrrateoID,Activo,AbonoA,UsuarioCreacionID,FechaCreacion) values ('012','Gastos Centros Fijos',6,2,1,'CUENTA',1,GETDATE())
insert INTO Costo (ClaveContable,Descripcion,TipoCostoID,TipoProrrateoID,Activo,AbonoA,UsuarioCreacionID,FechaCreacion) values ('013','Gastos Praderas Fijos',6,1,1,'CUENTA',1,GETDATE())
insert INTO Costo (ClaveContable,Descripcion,TipoCostoID,TipoProrrateoID,Activo,AbonoA,UsuarioCreacionID,FechaCreacion) values ('014','Alimento En Centro',2,4,1,'CUENTA',1,GETDATE())
insert INTO Costo (ClaveContable,Descripcion,TipoCostoID,TipoProrrateoID,Activo,AbonoA,UsuarioCreacionID,FechaCreacion) values ('015','Medicamento En Centro',3,4,1,'CUENTA',1,GETDATE())
insert INTO Costo (ClaveContable,Descripcion,TipoCostoID,TipoProrrateoID,Activo,AbonoA,UsuarioCreacionID,FechaCreacion) values ('016','Medicamento De Implante',3,1,1,'CUENTA',1,GETDATE())
insert INTO Costo (ClaveContable,Descripcion,TipoCostoID,TipoProrrateoID,Activo,AbonoA,UsuarioCreacionID,FechaCreacion) values ('017','Medicamento De Reimplante',3,1,1,'CUENTA',1,GETDATE())
insert INTO Costo (ClaveContable,Descripcion,TipoCostoID,TipoProrrateoID,Activo,AbonoA,UsuarioCreacionID,FechaCreacion) values ('018','Medicamento Enfermeria',3,1,1,'CUENTA',1,GETDATE())
insert INTO Costo (ClaveContable,Descripcion,TipoCostoID,TipoProrrateoID,Activo,AbonoA,UsuarioCreacionID,FechaCreacion) values ('019','Seguro De Mortandad Corrales',5,4,1,'PROVEEDOR',1,GETDATE())
insert INTO Costo (ClaveContable,Descripcion,TipoCostoID,TipoProrrateoID,Activo,AbonoA,UsuarioCreacionID,FechaCreacion) values ('020','Seguro De Transportes',5,4,1,'PROVEEDOR',1,GETDATE())
insert INTO Costo (ClaveContable,Descripcion,TipoCostoID,TipoProrrateoID,Activo,AbonoA,UsuarioCreacionID,FechaCreacion) values ('021','Seguro De Ganado En Centro',5,4,1,'PROVEEDOR',1,GETDATE())
insert INTO Costo (ClaveContable,Descripcion,TipoCostoID,TipoProrrateoID,Activo,AbonoA,UsuarioCreacionID,FechaCreacion) values ('022','Seguro De Enfermedades Exoticas',5,4,1,'PROVEEDOR',1,GETDATE())
insert INTO Costo (ClaveContable,Descripcion,TipoCostoID,TipoProrrateoID,Activo,AbonoA,UsuarioCreacionID,FechaCreacion) values ('023','Seguro Alta Mortandad Pradera',5,1,1,'PROVEEDOR',1,GETDATE())
insert INTO Costo (ClaveContable,Descripcion,TipoCostoID,TipoProrrateoID,Activo,AbonoA,UsuarioCreacionID,FechaCreacion) values ('024','Renta',7,4,1,'CUENTA',1,GETDATE())
insert INTO Costo (ClaveContable,Descripcion,TipoCostoID,TipoProrrateoID,Activo,AbonoA,UsuarioCreacionID,FechaCreacion) values ('025','Alimento En Descanso',2,1,1,'CUENTA',1,GETDATE())
insert INTO Costo (ClaveContable,Descripcion,TipoCostoID,TipoProrrateoID,Activo,AbonoA,UsuarioCreacionID,FechaCreacion) values ('026','Medicamento En Descanso',3,1,1,'CUENTA',1,GETDATE())
insert INTO Costo (ClaveContable,Descripcion,TipoCostoID,TipoProrrateoID,Activo,AbonoA,UsuarioCreacionID,FechaCreacion) values ('027','Manejo De Ganado',7,1,1,'CUENTA',1,GETDATE())
insert INTO Costo (ClaveContable,Descripcion,TipoCostoID,TipoProrrateoID,Activo,AbonoA,UsuarioCreacionID,FechaCreacion) values ('028','Alimento En Cadis',2,1,1,'CUENTA',1,GETDATE())
insert INTO Costo (ClaveContable,Descripcion,TipoCostoID,TipoProrrateoID,Activo,AbonoA,UsuarioCreacionID,FechaCreacion) values ('029','Medicamento En Cadis',3,1,1,'CUENTA',1,GETDATE())
insert INTO Costo (ClaveContable,Descripcion,TipoCostoID,TipoProrrateoID,Activo,AbonoA,UsuarioCreacionID,FechaCreacion) values ('030','Costo De Pradera',7,1,1,'CUENTA',1,GETDATE())
insert INTO Costo (ClaveContable,Descripcion,TipoCostoID,TipoProrrateoID,Activo,AbonoA,UsuarioCreacionID,FechaCreacion) values ('031','Medicamento En Pradera',3,1,1,'CUENTA',1,GETDATE())
insert INTO Costo (ClaveContable,Descripcion,TipoCostoID,TipoProrrateoID,Activo,AbonoA,UsuarioCreacionID,FechaCreacion) values ('032','Baños',7,1,1,'CUENTA',1,GETDATE())
insert INTO Costo (ClaveContable,Descripcion,TipoCostoID,TipoProrrateoID,Activo,AbonoA,UsuarioCreacionID,FechaCreacion) values ('008','Demoras',4,1,1,'PROVEEDOR',1,GETDATE())