//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.36365
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIE.Services.ServicioValidaCreditoClientes {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://SuKarne.com/pi/SBX/ValidaCreditoClientes", ConfigurationName="ServicioValidaCreditoClientes.SI_OS_SBX_to_ECC_ValidaCreditoClientes")]
    public interface SI_OS_SBX_to_ECC_ValidaCreditoClientes {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación SI_OS_SBX_to_ECC_ValidaCreditoClientes no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SIE.Services.ServicioValidaCreditoClientes.SI_OS_SBX_to_ECC_ValidaCreditoClientesResponse SI_OS_SBX_to_ECC_ValidaCreditoClientes(SIE.Services.ServicioValidaCreditoClientes.SI_OS_SBX_to_ECC_ValidaCreditoClientesRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://SuKarne.com/pi/SBX/ValidaCreditoClientes")]
    public partial class DT_SBK_ValidaCreditoClientes_Request : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string clienteField;
        
        private string importeField;
        
        private string monedaField;
        
        private string sociedadField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
                this.RaisePropertyChanged("Cliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Importe {
            get {
                return this.importeField;
            }
            set {
                this.importeField = value;
                this.RaisePropertyChanged("Importe");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
                this.RaisePropertyChanged("Moneda");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Sociedad {
            get {
                return this.sociedadField;
            }
            set {
                this.sociedadField = value;
                this.RaisePropertyChanged("Sociedad");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://SuKarne.com/pi/SBX/ValidaCreditoClientes")]
    public partial class DT_SBK_ValidaCreditoClientes_Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultadoField;
        
        private string mensajeField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
                this.RaisePropertyChanged("Resultado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("Mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_OS_SBX_to_ECC_ValidaCreditoClientesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SuKarne.com/pi/SBX/ValidaCreditoClientes", Order=0)]
        public SIE.Services.ServicioValidaCreditoClientes.DT_SBK_ValidaCreditoClientes_Request MT_SBK_ValidaCreditoClientes_Request;
        
        public SI_OS_SBX_to_ECC_ValidaCreditoClientesRequest() {
        }
        
        public SI_OS_SBX_to_ECC_ValidaCreditoClientesRequest(SIE.Services.ServicioValidaCreditoClientes.DT_SBK_ValidaCreditoClientes_Request MT_SBK_ValidaCreditoClientes_Request) {
            this.MT_SBK_ValidaCreditoClientes_Request = MT_SBK_ValidaCreditoClientes_Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_OS_SBX_to_ECC_ValidaCreditoClientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SuKarne.com/pi/SBX/ValidaCreditoClientes", Order=0)]
        public SIE.Services.ServicioValidaCreditoClientes.DT_SBK_ValidaCreditoClientes_Response MT_SBK_ValidaCreditoClientes_Response;
        
        public SI_OS_SBX_to_ECC_ValidaCreditoClientesResponse() {
        }
        
        public SI_OS_SBX_to_ECC_ValidaCreditoClientesResponse(SIE.Services.ServicioValidaCreditoClientes.DT_SBK_ValidaCreditoClientes_Response MT_SBK_ValidaCreditoClientes_Response) {
            this.MT_SBK_ValidaCreditoClientes_Response = MT_SBK_ValidaCreditoClientes_Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_OS_SBX_to_ECC_ValidaCreditoClientesChannel : SIE.Services.ServicioValidaCreditoClientes.SI_OS_SBX_to_ECC_ValidaCreditoClientes, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_OS_SBX_to_ECC_ValidaCreditoClientesClient : System.ServiceModel.ClientBase<SIE.Services.ServicioValidaCreditoClientes.SI_OS_SBX_to_ECC_ValidaCreditoClientes>, SIE.Services.ServicioValidaCreditoClientes.SI_OS_SBX_to_ECC_ValidaCreditoClientes {
        
        public SI_OS_SBX_to_ECC_ValidaCreditoClientesClient() {
        }
        
        public SI_OS_SBX_to_ECC_ValidaCreditoClientesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_OS_SBX_to_ECC_ValidaCreditoClientesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_OS_SBX_to_ECC_ValidaCreditoClientesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_OS_SBX_to_ECC_ValidaCreditoClientesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SIE.Services.ServicioValidaCreditoClientes.SI_OS_SBX_to_ECC_ValidaCreditoClientesResponse SIE.Services.ServicioValidaCreditoClientes.SI_OS_SBX_to_ECC_ValidaCreditoClientes.SI_OS_SBX_to_ECC_ValidaCreditoClientes(SIE.Services.ServicioValidaCreditoClientes.SI_OS_SBX_to_ECC_ValidaCreditoClientesRequest request) {
            return base.Channel.SI_OS_SBX_to_ECC_ValidaCreditoClientes(request);
        }
        
        public SIE.Services.ServicioValidaCreditoClientes.DT_SBK_ValidaCreditoClientes_Response SI_OS_SBX_to_ECC_ValidaCreditoClientes(SIE.Services.ServicioValidaCreditoClientes.DT_SBK_ValidaCreditoClientes_Request MT_SBK_ValidaCreditoClientes_Request) {
            SIE.Services.ServicioValidaCreditoClientes.SI_OS_SBX_to_ECC_ValidaCreditoClientesRequest inValue = new SIE.Services.ServicioValidaCreditoClientes.SI_OS_SBX_to_ECC_ValidaCreditoClientesRequest();
            inValue.MT_SBK_ValidaCreditoClientes_Request = MT_SBK_ValidaCreditoClientes_Request;
            SIE.Services.ServicioValidaCreditoClientes.SI_OS_SBX_to_ECC_ValidaCreditoClientesResponse retVal = ((SIE.Services.ServicioValidaCreditoClientes.SI_OS_SBX_to_ECC_ValidaCreditoClientes)(this)).SI_OS_SBX_to_ECC_ValidaCreditoClientes(inValue);
            return retVal.MT_SBK_ValidaCreditoClientes_Response;
        }
    }
}
