Insert Into TipoOrganizacion (TipoProcesoID, Descripcion, Activo) VALUES (1, 'Corporativo',1) 
Insert Into TipoOrganizacion (TipoProcesoID, Descripcion, Activo) VALUES (3, 'Ganadera',1) 
Insert Into TipoOrganizacion (TipoProcesoID, Descripcion, Activo) VALUES (1, 'Compra Directa',1) 
Insert Into TipoOrganizacion (TipoProcesoID, Descripcion, Activo) VALUES (1, 'Centro',1) 
Insert Into TipoOrganizacion (TipoProcesoID, Descripcion, Activo) VALUES (1, 'Praderas',1) 
Insert Into TipoOrganizacion (TipoProcesoID, Descripcion, Activo) VALUES (1, 'Descanso',1) 
Insert Into TipoOrganizacion (TipoProcesoID, Descripcion, Activo) VALUES (1, 'Cadis',1)
Insert Into TipoOrganizacion (TipoProcesoID, Descripcion, Activo) VALUES (3, 'Intensivo',1) 
Insert Into TipoOrganizacion (TipoProcesoID, Descripcion, Activo) VALUES (2, 'Maquila',1) 
