INSERT INTO Modulo (Descripcion, [Control], Activo, Orden) VALUES ('Catálogos', 'Catalogos', 1, 1) 
INSERT INTO Modulo (Descripcion, [Control], Activo, Orden) VALUES ('Seguridad', 'Seguridad', 1, 2) 
INSERT INTO Modulo (Descripcion, [Control], Activo, Orden) VALUES ('Configuración','Configuracion', 1, 3)
INSERT INTO Modulo (Descripcion, [Control], Activo, Orden) VALUES ('Recepción','Recepcion', 1, 4)
INSERT INTO Modulo (Descripcion, [Control], Activo, Orden) VALUES ('Manejo','Manejo', 1, 5)
INSERT INTO Modulo (Descripcion, [Control], Activo, Orden) VALUES ('Sanidad','Sanidad', 1, 6)
INSERT INTO Modulo (Descripcion, [Control], Activo, Orden) VALUES ('Alimentación','Alimentacion', 1, 9)
INSERT INTO Modulo (Descripcion, [Control], Activo, Orden) VALUES ('Reportes','Reporte', 1, 8)
INSERT INTO Modulo (Descripcion, [Control], Activo, Orden) VALUES ('Materia Prima','MateriaPrima', 1, 8)
INSERT INTO Modulo (Descripcion, [Control], Activo, Orden) VALUES ('Planta de Alimentos','PlantaAlimentos', 1, 10)
INSERT INTO Modulo (Descripcion, [Control], Activo, Orden) VALUES ('Administración','Administracion', 1, 11)
INSERT INTO Modulo (Descripcion, [Control], Activo, Orden) VALUES ('Almacén','Almacen', 1, 12)
INSERT INTO Modulo (Descripcion, [Control], Activo, Orden) VALUES ('Calidad','Calidad', 1, 7)
