SET IDENTITY_INSERT [dbo].[TipoPoliza] ON 
GO

INSERT [dbo].[TipoPoliza] ([TipoPolizaID], [Descripcion], [ClavePoliza], [PostFijoRef3], [TextoDocumento], [ImprimePoliza], [Activo], [FechaCreacion], [UsuarioCreacionID], [FechaModificacion], [UsuarioModificacionID]) VALUES (1, N'Entrada Ganado', N'EG', N'GF', N'ENTRADA DE GANADO', 1, 1, CAST(0xA304027E AS SmallDateTime), 1, NULL, NULL)
INSERT [dbo].[TipoPoliza] ([TipoPolizaID], [Descripcion], [ClavePoliza], [PostFijoRef3], [TextoDocumento], [ImprimePoliza], [Activo], [FechaCreacion], [UsuarioCreacionID], [FechaModificacion], [UsuarioModificacionID]) VALUES (2, N'Consumo de Producto', N'SP', N'AG', N'CONSUMO DE PRODUCTO', 0, 1, CAST(0xA304027E AS SmallDateTime), 1, NULL, NULL)
INSERT [dbo].[TipoPoliza] ([TipoPolizaID], [Descripcion], [ClavePoliza], [PostFijoRef3], [TextoDocumento], [ImprimePoliza], [Activo], [FechaCreacion], [UsuarioCreacionID], [FechaModificacion], [UsuarioModificacionID]) VALUES (3, N'Salida por Venta', N'SV', N'GF', N'SALIDA POR VENTA', 1, 1, CAST(0xA3680287 AS SmallDateTime), 1, NULL, NULL)
INSERT [dbo].[TipoPoliza] ([TipoPolizaID], [Descripcion], [ClavePoliza], [PostFijoRef3], [TextoDocumento], [ImprimePoliza], [Activo], [FechaCreacion], [UsuarioCreacionID], [FechaModificacion], [UsuarioModificacionID]) VALUES (4, N'Salida por Muerte', N'SM', N'GF', N'SALIDA POR MUERTE', 1, 1, CAST(0xA3680287 AS SmallDateTime), 1, NULL, NULL)
INSERT [dbo].[TipoPoliza] ([TipoPolizaID], [Descripcion], [ClavePoliza], [PostFijoRef3], [TextoDocumento], [ImprimePoliza], [Activo], [FechaCreacion], [UsuarioCreacionID], [FechaModificacion], [UsuarioModificacionID]) VALUES (5, N'Consumo Alimento', N'CA', N'GF', N'CONSUMO ALIMENTO', 0, 1, CAST(0xA371029D AS SmallDateTime), 3, NULL, NULL)
INSERT [dbo].[TipoPoliza] ([TipoPolizaID], [Descripcion], [ClavePoliza], [PostFijoRef3], [TextoDocumento], [ImprimePoliza], [Activo], [FechaCreacion], [UsuarioCreacionID], [FechaModificacion], [UsuarioModificacionID]) VALUES (6, N'Entrada Compra', N'EC', N'AG', N'ENTRADA POR COMPRA', 1, 1, CAST(0xA371029D AS SmallDateTime), 3, NULL, NULL)
INSERT [dbo].[TipoPoliza] ([TipoPolizaID], [Descripcion], [ClavePoliza], [PostFijoRef3], [TextoDocumento], [ImprimePoliza], [Activo], [FechaCreacion], [UsuarioCreacionID], [FechaModificacion], [UsuarioModificacionID]) VALUES (7, N'Salida por Ajuste', N'SA', N'AG', N'SALIDA POR AJUSTE', 0, 1, CAST(0xA38504E1 AS SmallDateTime), 1, NULL, NULL)
INSERT [dbo].[TipoPoliza] ([TipoPolizaID], [Descripcion], [ClavePoliza], [PostFijoRef3], [TextoDocumento], [ImprimePoliza], [Activo], [FechaCreacion], [UsuarioCreacionID], [FechaModificacion], [UsuarioModificacionID]) VALUES (8, N'Salida por Traspaso', N'ST', N'AG', N'SALIDA DE MATERIA PRIMA', 1, 1, CAST(0xA38504E1 AS SmallDateTime), 1, NULL, NULL)
INSERT [dbo].[TipoPoliza] ([TipoPolizaID], [Descripcion], [ClavePoliza], [PostFijoRef3], [TextoDocumento], [ImprimePoliza], [Activo], [FechaCreacion], [UsuarioCreacionID], [FechaModificacion], [UsuarioModificacionID]) VALUES (9, N'Entrada por Ajuste', N'EA', N'AG', N'ENTRADA POR AJUSTE', 0, 1, CAST(0xA38504E1 AS SmallDateTime), 1, NULL, NULL)
INSERT [dbo].[TipoPoliza] ([TipoPolizaID], [Descripcion], [ClavePoliza], [PostFijoRef3], [TextoDocumento], [ImprimePoliza], [Activo], [FechaCreacion], [UsuarioCreacionID], [FechaModificacion], [UsuarioModificacionID]) VALUES (10, N'Salida por Consumo', N'SC', N'AG', N'SALIDA DE MATERIA PRIMA', 1, 1, CAST(0xA38504E1 AS SmallDateTime), 1, NULL, NULL)
INSERT [dbo].[TipoPoliza] ([TipoPolizaID], [Descripcion], [ClavePoliza], [PostFijoRef3], [TextoDocumento], [ImprimePoliza], [Activo], [FechaCreacion], [UsuarioCreacionID], [FechaModificacion], [UsuarioModificacionID]) VALUES (11, N'Salida por Venta de Producto', N'SV', N'AG', N'SALIDA POR PRODUCTO', 1, 1, CAST(0xA38504E1 AS SmallDateTime), 1, NULL, NULL)
INSERT [dbo].[TipoPoliza] ([TipoPolizaID], [Descripcion], [ClavePoliza], [PostFijoRef3], [TextoDocumento], [ImprimePoliza], [Activo], [FechaCreacion], [UsuarioCreacionID], [FechaModificacion], [UsuarioModificacionID]) VALUES (12, N'Pase a Proceso', N'PP', N'AG', N'PRODUCCION PASE A PROCESO', 1, 1, CAST(0xA38504E1 AS SmallDateTime), 1, NULL, NULL)
INSERT [dbo].[TipoPoliza] ([TipoPolizaID], [Descripcion], [ClavePoliza], [PostFijoRef3], [TextoDocumento], [ImprimePoliza], [Activo], [FechaCreacion], [UsuarioCreacionID], [FechaModificacion], [UsuarioModificacionID]) VALUES (13, N'Producción de Alimento', N'PA', N'AG', N'SALIDA DE MATERIA PRIMA', 1, 1, CAST(0xA38504E1 AS SmallDateTime), 1, NULL, NULL)
INSERT [dbo].[TipoPoliza] ([TipoPolizaID], [Descripcion], [ClavePoliza], [PostFijoRef3], [TextoDocumento], [ImprimePoliza], [Activo], [FechaCreacion], [UsuarioCreacionID], [FechaModificacion], [UsuarioModificacionID]) VALUES (14, N'Entrada Por Compra Almacen General', N'EC', N'AG', N'ENTRADA POR COMPRA ALMACEN GENERAL', 0, 1, CAST(0xA3850419 AS SmallDateTime), 1, NULL, NULL)
INSERT [dbo].[TipoPoliza] ([TipoPolizaID], [Descripcion], [ClavePoliza], [PostFijoRef3], [TextoDocumento], [ImprimePoliza], [Activo], [FechaCreacion], [UsuarioCreacionID], [FechaModificacion], [UsuarioModificacionID]) VALUES (15, N'Gastos al Inventario', N'CD', N'GF', N'GASTOS DE OPERACION', 0, 1, CAST(0xA3850408 AS SmallDateTime), 1, NULL, NULL)
INSERT [dbo].[TipoPoliza] ([TipoPolizaID], [Descripcion], [ClavePoliza], [PostFijoRef3], [TextoDocumento], [ImprimePoliza], [Activo], [FechaCreacion], [UsuarioCreacionID], [FechaModificacion], [UsuarioModificacionID]) VALUES (16, N'Gastos de Materia Prima', N'SA', N'AG', N'GASTOS DE MATERIA PRIMA', 0, 1, CAST(0xA38504E3 AS SmallDateTime), 1, NULL, NULL)
INSERT [dbo].[TipoPoliza] ([TipoPolizaID], [Descripcion], [ClavePoliza], [PostFijoRef3], [TextoDocumento], [ImprimePoliza], [Activo], [FechaCreacion], [UsuarioCreacionID], [FechaModificacion], [UsuarioModificacionID]) VALUES (17, N'Poliza Contrato', N'CB', N'AG', N'CONTRATO BODEGA DE TERCEROS', 0, 1, CAST(0xA39504B8 AS SmallDateTime), 1, NULL, NULL)
INSERT [dbo].[TipoPoliza] ([TipoPolizaID], [Descripcion], [ClavePoliza], [PostFijoRef3], [TextoDocumento], [ImprimePoliza], [Activo], [FechaCreacion], [UsuarioCreacionID], [FechaModificacion], [UsuarioModificacionID]) VALUES (18, N'Poliza Contrato Transito', N'CT', N'AG', N'CONTRATO TRANSITO', 0, 1, CAST(0xA39504BD AS SmallDateTime), 1, NULL, NULL)
INSERT [dbo].[TipoPoliza] ([TipoPolizaID], [Descripcion], [ClavePoliza], [PostFijoRef3], [TextoDocumento], [ImprimePoliza], [Activo], [FechaCreacion], [UsuarioCreacionID], [FechaModificacion], [UsuarioModificacionID]) VALUES (19, N'Poliza Contrato Otros Costos', N'OC', N'AG', N'CONTRATO OTROS COSTOS', 0, 1, CAST(0xA3960293 AS SmallDateTime), 1, NULL, NULL)
INSERT [dbo].[TipoPoliza] ([TipoPolizaID], [Descripcion], [ClavePoliza], [PostFijoRef3], [TextoDocumento], [ImprimePoliza], [Activo], [FechaCreacion], [UsuarioCreacionID], [FechaModificacion], [UsuarioModificacionID]) VALUES (20, N'Poliza Contrato Parcialidades', N'CP', N'AG', N'CONTRATO PARCIALIDADES', 0, 1, CAST(0xA3960293 AS SmallDateTime), 1, NULL, NULL)
INSERT [dbo].[TipoPoliza] ([TipoPolizaID], [Descripcion], [ClavePoliza], [PostFijoRef3], [TextoDocumento], [ImprimePoliza], [Activo], [FechaCreacion], [UsuarioCreacionID], [FechaModificacion], [UsuarioModificacionID]) VALUES (21, N'Poliza Contrato SubProductos', N'CS', N'AG', N'CONTRATO SUBPRODUCTOS', 0, 1, CAST(0xA3960293 AS SmallDateTime), 1, NULL, NULL)
INSERT INTO TipoPoliza(Descripcion, ClavePoliza, PostFijoRef3, TextoDocumento, Activo, FechaCreacion, UsuarioCreacionID)
VALUES('Poliza de Sacrificio', 'PS', 'GF', 'FACTURACION SALIDA SACRIFICIO', 1, GETDATE(), 1)

INSERT INTO TipoPoliza(Descripcion, ClavePoliza, PostFijoRef3, TextoDocumento, Activo, FechaCreacion, UsuarioCreacionID)
VALUES('Poliza de Premezcla', 'PM', 'AG', 'FACTURACION PREMEZCLA', 1, GETDATE(), 1)

SET IDENTITY_INSERT [dbo].[TipoPoliza] OFF
GO
