INSERT INTO TipoContrato (Descripcion, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('Patio', 1, GETDATE(), 1)
INSERT INTO TipoContrato (Descripcion, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('Bodega Externa', 1, GETDATE(), 1)
INSERT INTO TipoContrato (Descripcion, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('Bodega Tercero', 1, GETDATE(), 1)
INSERT INTO TipoContrato (Descripcion, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('Bodega Normal', 1, GETDATE(), 1)
INSERT INTO TipoContrato (Descripcion, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('Proceso', 1, GETDATE(), 1)
INSERT INTO TipoContrato (Descripcion, Activo, FechaCreacion, UsuarioCreacionID) VALUES ('En Tránsito', 1, GETDATE(), 1)
