INSERT INTO Operador (Nombre, ApellidoPaterno, ApellidoMaterno, CodigoSAP, RolID, Activo, OrganizacionID, FechaCreacion, UsuarioCreacionID)
VALUES ('HECTOR MIGUEL', 'RAMIREZ', 'ESTRADA', '70012391', 10, 1, 4,  GETDATE(), 1)
INSERT INTO Operador (Nombre, ApellidoPaterno, ApellidoMaterno, CodigoSAP, RolID, Activo, OrganizacionID, FechaCreacion, UsuarioCreacionID)
VALUES ('DIEGO ALBERTO', 'YAMAGUCHI', 'LOPEZ', '70012915', 10,1, 1, GETDATE(), 1) 
INSERT INTO Operador (Nombre, ApellidoPaterno, ApellidoMaterno, CodigoSAP, RolID, Activo, OrganizacionID,FechaCreacion, UsuarioCreacionID)
VALUES ('JOSE ARTURO', 'RAMIREZ', 'CASTRO', '70004783', 10, 1, 2, GETDATE(), 1)
