INSERT INTO InterfaceCosto (CostoID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (14,24,'C',GETDATE(),1)
INSERT INTO InterfaceCosto (CostoID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (15,25,'C',GETDATE(),1)
INSERT INTO InterfaceCosto (CostoID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (1,26,'C',GETDATE(),1)
INSERT INTO InterfaceCosto (CostoID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (4, 17, 'P', GETDATE(), 1)
INSERT INTO InterfaceCosto (CostoID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (6, 18, 'P', GETDATE(), 1)
INSERT INTO InterfaceCosto (CostoID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (7, 20, 'P', GETDATE(), 1)
INSERT INTO InterfaceCosto (CostoID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (5, 21, 'P', GETDATE(), 1)
INSERT INTO InterfaceCosto (CostoID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (14, 24, 'P', GETDATE(), 1)
INSERT INTO InterfaceCosto (CostoID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (15, 25, 'P', GETDATE(), 1)
INSERT INTO InterfaceCosto (CostoID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (1, 26, 'P', GETDATE(), 1)
INSERT INTO InterfaceCosto (CostoID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (28, 29, 'P', GETDATE(), 1)
INSERT INTO InterfaceCosto (CostoID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (31, 30, 'P', GETDATE(), 1)
INSERT INTO InterfaceCosto (CostoID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (31, 31, 'P', GETDATE(), 1)
INSERT INTO InterfaceCosto (CostoID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (31, 32, 'P', GETDATE(), 1)
INSERT INTO InterfaceCosto (CostoID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (2, 33, 'P', GETDATE(), 1)
INSERT INTO InterfaceCosto (CostoID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (4, 34, 'P', GETDATE(), 1)
INSERT INTO InterfaceCosto (CostoID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (3, 35, 'P', GETDATE(), 1)
INSERT INTO InterfaceCosto (CostoID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (9, 37, 'P', GETDATE(), 1)
INSERT INTO InterfaceCosto (CostoID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (12, 38, 'P', GETDATE(), 1)
INSERT INTO InterfaceCosto (CostoID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (10, 39, 'P', GETDATE(), 1)
INSERT INTO InterfaceCosto (CostoID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (11, 43, 'P', GETDATE(), 1)
INSERT INTO InterfaceCosto (CostoID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (27, 44, 'P', GETDATE(), 1)
INSERT INTO InterfaceCosto (CostoID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (8, 45, 'P', GETDATE(), 1)
INSERT INTO InterfaceCosto (CostoID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (18, 47, 'P', GETDATE(), 1)
INSERT INTO InterfaceCosto (CostoID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (17, 49, 'P', GETDATE(), 1)
INSERT INTO InterfaceCosto (CostoID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (4, 50, 'P', GETDATE(), 1)
INSERT INTO InterfaceCosto (CostoID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (30, 52, 'P', GETDATE(), 1)
INSERT INTO InterfaceCosto (CostoID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (3, 54, 'P', GETDATE(), 1)
INSERT INTO InterfaceCosto (CostoID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (24, 55, 'P', GETDATE(), 1)
INSERT INTO InterfaceCosto (CostoID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (13, 58, 'P', GETDATE(), 1)
INSERT INTO InterfaceCosto (CostoID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (13, 59, 'P', GETDATE(), 1)
INSERT INTO InterfaceCosto (CostoID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (13, 60, 'P', GETDATE(), 1)
INSERT INTO InterfaceCosto (CostoID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (16, 64, 'P', GETDATE(), 1)
INSERT INTO InterfaceCosto (CostoID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (17, 65, 'P', GETDATE(), 1)
INSERT INTO InterfaceCosto (CostoID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (28, 66, 'P', GETDATE(), 1)
INSERT INTO InterfaceCosto (CostoID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (29, 67, 'P', GETDATE(), 1)
INSERT INTO InterfaceCosto (CostoID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (20, 81, 'P', GETDATE(), 1)