INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (1, 1, 'G', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (2, 2, 'G', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (3, 3, 'G', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (4, 4, 'G', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (5, 6, 'G', GETDATE(), 1)

INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (8, 1, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (9, 2, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (10, 3, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (11, 4, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (12, 5, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (13, 6, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (14, 8, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (15, 9, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (16, 10, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (17, 12, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (18, 13, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (19, 14, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (20, 15, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (21, 16, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (22, 17, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (23, 18, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (24, 19, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (25, 20, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (26, 24, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (27, 28, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (28, 29, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (29, 35, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (30, 36, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (31, 37, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (32, 38, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (33, 39, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (34, 40, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (35, 41, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (36, 42, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (37, 43, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (38, 44, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (39, 45, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (40, 46, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (41, 47, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (42, 49, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (43, 50, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (44, 51, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (45, 53, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (46, 54, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (47, 59, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (48, 60, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (49, 61, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (50, 62, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (51, 69, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (52, 70, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (53, 71, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (54, 72, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (55, 73, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (56, 74, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (57, 75, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (58, 76, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (59, 81, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (60, 85, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (61, 87, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (62, 89, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (63, 93, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (64, 95, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (65, 96, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (66, 98, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (67, 100, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (68, 101, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (69, 102, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (70, 103, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (71, 104, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (72, 104, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (73, 105, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (74, 105, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (75, 106, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (76, 107, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (77, 107, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (78, 108, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (79, 108, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (80, 109, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (81, 112, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (82, 114, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (83, 115, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (84, 116, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (85, 117, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (86, 120, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (87, 121, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (88, 122, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (89, 123, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (90, 126, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (91, 127, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (92, 128, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (93, 129, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (94, 131, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (95, 132, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (96, 133, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (97, 135, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (98, 136, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (99, 137, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (100, 138, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (101, 139, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (102, 140, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (103, 141, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (104, 142, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (105, 143, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (106, 144, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (107, 145, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (108, 146, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (109, 147, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (110, 148, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (111, 150, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (112, 152, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (113, 153, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (114, 154, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (115, 156, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (116, 157, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (117, 158, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (118, 159, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (119, 160, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (120, 161, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (121, 162, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (122, 163, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (123, 164, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (124, 165, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (125, 168, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (126, 170, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (127, 171, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (128, 172, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (129, 173, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (130, 176, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (131, 179, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (132, 182, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (133, 183, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (134, 184, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (135, 186, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (136, 190, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (137, 191, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (138, 192, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (139, 196, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (140, 197, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (141, 199, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (142, 210, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (143, 211, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (144, 212, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (145, 213, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (146, 214, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (147, 215, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (148, 216, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (149, 217, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (150, 218, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (151, 219, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (152, 220, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (153, 221, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (154, 222, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (155, 223, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (156, 224, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (157, 235, 'C', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (158, 239, 'C', GETDATE(), 1)

INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(166, 23, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(164, 14, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(206, 135, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(188, 117, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(182, 94, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(177, 80, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(204, 133, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(197, 126, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(178, 83, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(162, 10, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(219, 149, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(190, 119, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(180, 89, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(168, 32, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(165, 19, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(169, 35, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(200, 129, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(183, 98, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(195, 124, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(179, 87, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(216, 146, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(220, 150, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(201, 130, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(207, 136, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(203, 132, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(214, 143, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(184, 113, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(215, 144, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(211, 140, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(172, 53, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(213, 142, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(209, 138, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(189, 118, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(221, 151, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(223, 162, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(181, 93, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(210, 139, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(160, 8, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(198, 127, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(202, 131, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(174, 64, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(175, 65, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(173, 60, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(187, 116, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(186, 115, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(217, 147, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(199, 128, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(185, 114, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(192, 121, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(194, 123, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(205, 134, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(218, 148, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(222, 155, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(161, 9, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(170, 37, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(193, 122, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(212, 141, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(167, 25, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(163, 13, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(171, 44, 'P', GETDATE(), 1)
INSERT INTO InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES(196, 125, 'P', GETDATE(), 1)

INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (225, 82, 'P', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (226, 101, 'P', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (227, 152, 'P', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (228, 153, 'P', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (229, 154, 'P', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (230, 157, 'P', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (231, 158, 'P', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (232, 159, 'P', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (233, 160, 'P', GETDATE(), 1)
INSERT INTO	InterfaceOrganizacion (OrganizacionID, CodigoRelacion, TipoSistema, FechaCreacion, UsuarioCreacionID) VALUES (234, 161, 'P', GETDATE(), 1)