INSERT INTO [CausaSalida] ([Descripcion],[TipoMovimientoID],[Activo],[FechaCreacion],[UsuarioCreacionID]) VALUES ('Venta en pie', 11, 1, GETDATE(), 1)
INSERT INTO [CausaSalida] ([Descripcion],[TipoMovimientoID],[Activo],[FechaCreacion],[UsuarioCreacionID]) VALUES ('Alta/Recuperación',15,1,GETDATE(),1)
INSERT INTO [CausaSalida] ([Descripcion],[TipoMovimientoID],[Activo],[FechaCreacion],[UsuarioCreacionID]) VALUES ('Causa de fuerza mayor',16,1,GETDATE(),1)
INSERT INTO [CausaSalida] ([Descripcion],[TipoMovimientoID],[Activo],[FechaCreacion],[UsuarioCreacionID]) VALUES ('CRB',11,1,GETDATE(),1)
INSERT INTO [CausaSalida] ([Descripcion],[TipoMovimientoID],[Activo],[FechaCreacion],[UsuarioCreacionID]) VALUES ('Timpanismo',11,1,GETDATE(),1)
INSERT INTO [CausaSalida] ([Descripcion],[TipoMovimientoID],[Activo],[FechaCreacion],[UsuarioCreacionID]) VALUES ('Quebrado',11,1,GETDATE(),1)