INSERT INTO Grado (Descripcion,NivelGravedad,Activo,FechaCreacion,UsuarioCreacionID)
values ('1','L',1,GETDATE(),1)
INSERT INTO Grado (Descripcion,NivelGravedad,Activo,FechaCreacion,UsuarioCreacionID)
values ('2','L',1,GETDATE(),1)
INSERT INTO Grado (Descripcion,NivelGravedad,Activo,FechaCreacion,UsuarioCreacionID)
values ('3','G',1,GETDATE(),1)
INSERT INTO Grado (Descripcion,NivelGravedad,Activo,FechaCreacion,UsuarioCreacionID)
values ('4','G',1,GETDATE(),1)
INSERT INTO Grado (Descripcion,NivelGravedad,Activo,FechaCreacion,UsuarioCreacionID)
values ('5','G',1,GETDATE(),1)